import type { Locale } from "@/features/localization/catalog";

const copy = {
  en: {
    representativeMode: "Representative recipient",
    directMode: "Direct store or organizer",
    representativeSummary: "Participants pay the representative recipient directly. The recipient-funded amount is accounting only and creates no self-transfer.",
    directSummary: "Every payer sends directly to the external recipient. The full Bill total is assigned to payer slots.",
    recipient: "Recipient",
    billTotal: "Bill total",
    recipientFunded: "Recipient-funded amount",
    participantCollection: "Participant collection total",
    verified: "Verified total",
    remaining: "Remaining total",
    noTransfer: "No transfer",
    managementTitle: "Management access",
    managementBody: "For the Bill operator only. Do not send this link to participants.",
    readOnlyTitle: "Read-only progress",
    readOnlyBody: "For viewers who only need collection progress. It grants no management or payment access.",
    paymentAudience: "Send only to this payer",
    paymentBody: "This link is bound to the frozen payer address and amount. Do not send another payer's link.",
    copyManagement: "Copy management link",
    copyReadOnly: "Copy read-only link",
    copyPayment: "Copy payment link",
    copyInstructions: "Copy full payment instructions",
    copyRlusdSetup: "Copy RLUSD preparation instructions",
    copied: "Copied",
    capabilityWarning: "Each shared link has a different audience. Keep management access private and send each participant only their own payment link.",
    verifiedZero: "No verified payments yet",
  },
  ja: {
    representativeMode: "代表者が受け取る",
    directMode: "店舗・主催者へ直接支払う",
    representativeSummary: "参加者は代表者の受取先へ直接送金します。受取人負担額は会計上の記録で、自己送金は発生しません。",
    directSummary: "各支払者が外部の受取先へ直接送金します。請求総額の全額が支払枠へ割り当てられます。",
    recipient: "受取人",
    billTotal: "請求総額",
    recipientFunded: "受取人負担額",
    participantCollection: "参加者からの回収予定額",
    verified: "検証済み合計",
    remaining: "残額",
    noTransfer: "送金なし",
    managementTitle: "管理アクセス",
    managementBody: "請求の操作担当専用です。このリンクを参加者へ送らないでください。",
    readOnlyTitle: "閲覧専用の進捗",
    readOnlyBody: "回収状況だけを見る人向けです。管理権限や支払い権限はありません。",
    paymentAudience: "この支払者だけに送る",
    paymentBody: "このリンクは確定済みの支払者アドレスと金額に結び付いています。他の支払者のリンクを送らないでください。",
    copyManagement: "管理リンクをコピー",
    copyReadOnly: "閲覧専用リンクをコピー",
    copyPayment: "支払いリンクをコピー",
    copyInstructions: "完全な支払い案内をコピー",
    copyRlusdSetup: "RLUSD準備案内をコピー",
    copied: "コピーしました",
    capabilityWarning: "共有リンクごとに対象者が異なります。管理アクセスは非公開にし、各参加者には本人用の支払いリンクだけを送ってください。",
    verifiedZero: "検証済み支払いはまだありません",
  },
  ko: {
    representativeMode: "대표 수취인",
    directMode: "상점 또는 주최자에게 직접 결제",
    representativeSummary: "참가자는 대표 수취인에게 직접 전송합니다. 수취인 부담 금액은 회계 기록이며 자기 전송을 만들지 않습니다.",
    directSummary: "각 결제자가 외부 수취인에게 직접 전송합니다. 전체 청구 금액이 결제 슬롯에 배정됩니다.",
    recipient: "수취인",
    billTotal: "청구 총액",
    recipientFunded: "수취인 부담 금액",
    participantCollection: "참가자 예정 수금액",
    verified: "검증 완료 합계",
    remaining: "남은 금액",
    noTransfer: "전송 없음",
    managementTitle: "관리 접근",
    managementBody: "청구 운영자 전용입니다. 이 링크를 참가자에게 보내지 마십시오.",
    readOnlyTitle: "읽기 전용 진행",
    readOnlyBody: "수금 진행만 확인하는 사람을 위한 링크입니다. 관리나 결제 권한은 없습니다.",
    paymentAudience: "이 결제자에게만 전송",
    paymentBody: "이 링크는 고정된 결제자 주소와 금액에 연결됩니다. 다른 결제자의 링크를 보내지 마십시오.",
    copyManagement: "관리 링크 복사",
    copyReadOnly: "읽기 전용 링크 복사",
    copyPayment: "결제 링크 복사",
    copyInstructions: "전체 결제 안내 복사",
    copyRlusdSetup: "RLUSD 준비 안내 복사",
    copied: "복사됨",
    capabilityWarning: "공유 링크마다 대상이 다릅니다. 관리 접근은 비공개로 유지하고 각 참가자에게는 본인의 결제 링크만 보내십시오.",
    verifiedZero: "아직 검증된 결제가 없습니다",
  },
} as const;

export function reviewSharingCopy(locale: Locale) {
  return copy[locale] ?? copy.en;
}
