import type { Locale } from "./catalog";

const copy = {
  en: {
    title: "Review and recovery controls",
    body: "These controls are available only through the private management capability. They never mark a Payment as ledger-verified manually.",
    loadError: "Recovery controls are temporarily unavailable.",
    copyTitle: "Create a revised Bill",
    copyBody: "Copy the frozen mode, recipient, asset, title, payer labels, addresses, and final allocations into a new browser-local draft. The existing Bill and every existing link remain unchanged.",
    copyAction: "Copy into a new Bill draft",
    reviewTitle: "PaymentSlot requires review",
    expected: "Frozen expected facts",
    observed: "Observed review facts",
    payer: "Expected payer",
    recipient: "Recipient",
    amount: "Amount",
    invoice: "InvoiceID",
    reason: "Review reason",
    transaction: "Observed transaction",
    candidates: "Observed candidates",
    noObservation: "No structured observed facts are available. The slot remains blocked.",
    explorer: "Open observed transaction in XRPL Explorer",
    retryWarning: "A transaction may already have moved value. A new request can create a repeated payment. Group Pay will still reconcile validated ledger history before creating it.",
    acknowledgePrior: "I understand that a prior transaction may already exist.",
    acknowledgeRepeated: "I understand that authorizing another attempt may cause a repeated payment.",
    authorize: "Authorize another attempt",
    authorizing: "Authorizing",
    authorized: "Another attempt was explicitly authorized. The payer must still use their private payment link and Group Pay will reconcile first.",
    closeTitle: "Close this Bill incomplete",
    closeBody: "Closure preserves verified receipts and permanently stops new wallet handoffs for unpaid slots.",
    closeReason: "Closure reason",
    operatorClosed: "Operator ended collection",
    collectionEnded: "Collection period ended",
    acknowledgeStops: "I understand that no new Payment can start after closure.",
    acknowledgeRefunds: "I understand that Group Pay does not reverse or automatically refund verified transfers.",
    confirmation: "Type CLOSE_INCOMPLETE",
    close: "Close Bill incomplete",
    closing: "Closing",
    closedTitle: "Bill closed incomplete",
    closedBody: "Verified receipts remain available. Unpaid slots cannot start new Payments.",
    paidCount: "Paid slots",
    verifiedAmount: "Verified amount",
    unpaidAmount: "Unpaid amount",
    noRefund: "Closure does not refund or reverse any validated XRPL transfer.",
    actionError: "The recovery action could not be completed.",
  },
  ja: {
    title: "確認・復旧操作",
    body: "この操作は非公開の管理権限でのみ利用できます。Paymentを手動で台帳検証済みにする機能はありません。",
    loadError: "復旧操作を一時的に利用できません。",
    copyTitle: "修正版の請求を新規作成",
    copyBody: "固定済みのモード、受取人、資産、タイトル、支払者名、アドレス、最終割り当てを、このブラウザ内の新しい下書きへコピーします。既存の請求と既存リンクは一切変更されません。",
    copyAction: "新しい請求の下書きへコピー",
    reviewTitle: "支払い枠の確認が必要です",
    expected: "固定済みの予定条件",
    observed: "確認対象として観測された情報",
    payer: "支払予定ウォレット",
    recipient: "受取先",
    amount: "金額",
    invoice: "InvoiceID",
    reason: "確認理由",
    transaction: "観測トランザクション",
    candidates: "観測候補",
    noObservation: "構造化された観測情報はありません。この支払い枠は引き続き停止されています。",
    explorer: "XRPL Explorerで観測トランザクションを開く",
    retryWarning: "すでに資金が移動している可能性があります。新しい要求により重複支払いが発生するおそれがあります。新しい要求を作る前にも、Group Payは検証済み台帳履歴を照合します。",
    acknowledgePrior: "以前のトランザクションが存在する可能性を理解しました。",
    acknowledgeRepeated: "別の試行を許可すると重複支払いが起こり得ることを理解しました。",
    authorize: "別の試行を明示的に許可",
    authorizing: "許可中",
    authorized: "別の試行が明示的に許可されました。支払者は専用リンクを使用し、Group Payは先に台帳履歴を照合します。",
    closeTitle: "未完了として請求を終了",
    closeBody: "終了後も検証済みレシートを保持し、未払い枠の新しいウォレット要求を恒久的に停止します。",
    closeReason: "終了理由",
    operatorClosed: "操作担当が回収を終了",
    collectionEnded: "回収期間が終了",
    acknowledgeStops: "終了後は新しいPaymentを開始できないことを理解しました。",
    acknowledgeRefunds: "Group Payは検証済み送金を取り消したり自動返金したりしないことを理解しました。",
    confirmation: "CLOSE_INCOMPLETE と入力",
    close: "未完了として終了",
    closing: "終了処理中",
    closedTitle: "未完了として終了済み",
    closedBody: "検証済みレシートは保持されます。未払い枠から新しいPaymentは開始できません。",
    paidCount: "支払済み枠",
    verifiedAmount: "検証済み金額",
    unpaidAmount: "未払い金額",
    noRefund: "終了しても検証済みXRPL送金は返金・取消されません。",
    actionError: "復旧操作を完了できませんでした。",
  },
  ko: {
    title: "검토 및 복구 제어",
    body: "이 제어는 비공개 관리 기능에서만 사용할 수 있습니다. Payment를 수동으로 원장 검증 완료 상태로 만들 수 없습니다.",
    loadError: "복구 제어를 일시적으로 사용할 수 없습니다.",
    copyTitle: "수정된 새 청구서 만들기",
    copyBody: "고정된 모드, 수취인, 자산, 제목, 결제자 이름, 주소와 최종 배정을 브라우저의 새 초안으로 복사합니다. 기존 청구서와 기존 링크는 변경되지 않습니다.",
    copyAction: "새 청구서 초안으로 복사",
    reviewTitle: "PaymentSlot 검토가 필요합니다",
    expected: "고정된 예상 사실",
    observed: "관찰된 검토 사실",
    payer: "예상 결제 지갑",
    recipient: "수취인",
    amount: "금액",
    invoice: "InvoiceID",
    reason: "검토 사유",
    transaction: "관찰된 트랜잭션",
    candidates: "관찰된 후보",
    noObservation: "구조화된 관찰 사실이 없습니다. 슬롯은 계속 차단됩니다.",
    explorer: "XRPL Explorer에서 관찰 거래 열기",
    retryWarning: "이미 가치가 이동했을 수 있습니다. 새 요청은 중복 결제를 만들 수 있습니다. Group Pay는 새 요청 전에 검증된 원장 기록을 다시 대조합니다.",
    acknowledgePrior: "이전 트랜잭션이 이미 존재할 수 있음을 이해했습니다.",
    acknowledgeRepeated: "다른 시도를 허용하면 중복 결제가 발생할 수 있음을 이해했습니다.",
    authorize: "다른 시도 명시적으로 허용",
    authorizing: "허용 중",
    authorized: "다른 시도가 명시적으로 허용되었습니다. 결제자는 비공개 결제 링크를 사용해야 하며 Group Pay는 먼저 원장을 대조합니다.",
    closeTitle: "미완료 상태로 청구서 종료",
    closeBody: "검증 영수증은 보존하고 미결제 슬롯의 새 지갑 요청을 영구적으로 중지합니다.",
    closeReason: "종료 사유",
    operatorClosed: "운영자가 수금 종료",
    collectionEnded: "수금 기간 종료",
    acknowledgeStops: "종료 후 새 Payment를 시작할 수 없음을 이해했습니다.",
    acknowledgeRefunds: "Group Pay가 검증된 전송을 취소하거나 자동 환불하지 않음을 이해했습니다.",
    confirmation: "CLOSE_INCOMPLETE 입력",
    close: "미완료 상태로 종료",
    closing: "종료 중",
    closedTitle: "미완료 상태로 종료됨",
    closedBody: "검증 영수증은 유지됩니다. 미결제 슬롯은 새 Payment를 시작할 수 없습니다.",
    paidCount: "결제 완료 슬롯",
    verifiedAmount: "검증 금액",
    unpaidAmount: "미결제 금액",
    noRefund: "종료는 검증된 XRPL 전송을 환불하거나 취소하지 않습니다.",
    actionError: "복구 작업을 완료할 수 없습니다.",
  },
} as const;

export type BillRecoveryMessageKey = keyof (typeof copy)["en"];

export function billRecoveryTranslate(
  locale: Locale,
  key: BillRecoveryMessageKey,
) {
  return copy[locale]?.[key] ?? copy.en[key];
}
