export const SUPPORTED_LOCALES = ["en", "ja", "ko"] as const;

export type Locale = (typeof SUPPORTED_LOCALES)[number];

const en = {
  "language.label": "Language",
  "language.english": "English",
  "language.japanese": "日本語",
  "language.korean": "한국어",
  "nav.roadmap": "Roadmap",
  "nav.changelog": "Changelog",
  "nav.source": "Source",
  "nav.home": "Home",
  "home.eyebrow": "Non-custodial shared settlement",
  "home.title": "Split the cost.",
  "home.titleAccent": "Settle directly.",
  "home.description": "Create one shared bill in XRP or official RLUSD, give each participant a frozen obligation, and verify every direct payment on XRPL {network}.",
  "home.halted": "Mainnet payment creation is currently halted while the controlled release checklist is completed. The public interface remains visible, but it will not create payment requests until release approval.",
  "home.cta.create": "Create a {network} bill",
  "home.cta.status": "View bill creation status",
  "home.cta.docs": "Read the product foundation",
  "home.principle.approve.title": "You approve every payment",
  "home.principle.approve.body": "Participants review and sign with their own Xaman wallet.",
  "home.principle.direct.title": "Funds move directly",
  "home.principle.direct.body": "Group Pay never becomes an intermediate recipient or app balance.",
  "home.principle.verify.title": "Ledger-verified completion",
  "home.principle.verify.body": "A payment is not marked paid until the validated transaction matches.",
  "home.step.create.title": "Create",
  "home.step.create.body": "Set the recipient, Asset, total, and participant shares.",
  "home.step.sign.title": "Sign",
  "home.step.sign.body": "Each participant approves their own Payment in Xaman.",
  "home.step.verify.title": "Verify",
  "home.step.verify.body": "Group Pay confirms the validated transaction before completion.",
  "home.footer": "Non-custodial coordination and validated-ledger verification.",
  "bill.page.eyebrow": "Creator flow · XRPL {network}",
  "bill.page.title": "Create one bill. Send each person their exact share.",
  "bill.page.description": "Group Pay freezes the destination, Settlement Asset, and allocations, then creates a separate payment capability for every participant. Funds move directly from each participant wallet to the recipient wallet.",
  "bill.page.halted.title": "Mainnet bill creation is not publicly open yet",
  "bill.page.halted.body": "This deployment is operationally halted while controlled release checks are completed. No payment request can be created in this state. The page will enable automatically only after the reviewed Mainnet release configuration is published.",
  "bill.page.releaseStatus": "View release status",
  "bill.page.completedWork": "View completed work",
  "bill.form.eyebrow": "Shared bill",
  "bill.form.title": "Choose one Settlement Asset for the Bill",
  "bill.form.description": "Every participant pays the same frozen Asset on XRPL {network}. Nothing becomes payable until the review step is confirmed.",
  "bill.form.reviewing": "Validating bill review",
  "bill.form.review": "Review bill before freezing",
  "bill.form.error.review": "The bill could not be reviewed.",
  "bill.form.error.create": "The shared bill could not be created.",
  "bill.asset.legend": "Settlement Asset",
  "bill.asset.xrp": "Native XRP on XRPL {network}",
  "bill.asset.rlusd": "Official Ripple USD issued on XRPL {network}",
  "bill.asset.issuer": "Issuer {issuer}",
  "bill.asset.rlusdNotice": "The destination account must be ready to receive official RLUSD. The issuer and amount will be frozen with every participant slot.",
  "bill.field.title": "Bill title",
  "bill.field.destination": "Creator destination address",
  "bill.field.total": "Total",
  "bill.field.creatorShare": "Creator share",
  "bill.field.destinationTag": "Destination Tag",
  "bill.field.optional": "Optional",
  "bill.allocation.method": "Allocation method",
  "bill.allocation.description": "The server recomputes the final obligations before the Bill is frozen.",
  "bill.allocation.custom.label": "Custom Amount",
  "bill.allocation.custom.description": "Enter each participant obligation directly.",
  "bill.allocation.equal.label": "Equal",
  "bill.allocation.equal.description": "Split the participant portion evenly.",
  "bill.allocation.percentage.label": "Percentage",
  "bill.allocation.percentage.description": "Assign exact percentages totaling 100%.",
  "bill.allocation.shares.label": "Shares",
  "bill.allocation.shares.description": "Use positive whole-number relative weights.",
  "bill.participants.title": "Participants",
  "bill.participants.minimum": "At least two payment slots are required.",
  "bill.participants.add": "Add participant",
  "bill.participant.number": "Participant {number}",
  "bill.participant.remove": "Remove participant {number}",
  "bill.participant.label": "Label",
  "bill.participant.payer": "Expected payer address",
  "bill.participant.amount": "Assigned amount",
  "bill.participant.percentage": "Percentage",
  "bill.participant.shares": "Shares",
  "bill.participant.calculated": "Calculated obligation",
  "bill.remainder.title": "Assign the remainder explicitly",
  "bill.remainder.description.one": "The calculation leaves {units} smallest Asset unit. Group Pay will not discard or assign it silently.",
  "bill.remainder.description.many": "The calculation leaves {units} smallest Asset units. Group Pay will not discard or assign them silently.",
  "bill.remainder.creator.label": "Creator pays remainder",
  "bill.remainder.creator.description": "Add all remainder units to the creator share.",
  "bill.remainder.first.label": "First participant pays remainder",
  "bill.remainder.first.description": "Add all remainder units to participant 1.",
  "bill.remainder.selected.label": "Choose one participant",
  "bill.remainder.selected.description": "Add all remainder units to a selected participant.",
  "bill.remainder.manual.label": "Distribute manually",
  "bill.remainder.manual.description": "Split only the remainder units across participants.",
  "bill.remainder.participant": "Remainder participant",
  "bill.remainder.select": "Select participant",
  "bill.remainder.manualTotal": "Manual remainder increments must total exactly {units}.",
  "bill.remainder.unitsFor": "Remainder units for {participant}",
  "bill.status.exact": "Allocation exact",
  "bill.status.remainder": "Remainder rule required",
  "bill.status.incomplete": "Allocation incomplete",
  "bill.status.enterAll": "Enter the total, creator share, and every participant amount.",
  "bill.status.remaining": "{amount} {asset} remains to allocate.",
  "bill.status.over": "{amount} {asset} is allocated above the bill total.",
  "bill.status.matches": "Creator share and participant amounts match the {asset} total.",
  "bill.review.badge": "{network} review",
  "bill.review.exact": "Allocation exact",
  "bill.review.title": "Review before freezing",
  "bill.review.description": "Confirm every destination, payer, Asset, allocation rule, and amount. The next step freezes these conditions and creates one capability link per participant.",
  "bill.review.mainnet.title": "Real Mainnet payment links",
  "bill.review.mainnet.body": "Participants will sign transactions that move real XRP or RLUSD. Check the destination, payer addresses, Asset, and every amount before freezing this Bill.",
  "bill.review.billTotal": "Bill total",
  "bill.review.creatorShare": "Creator share",
  "bill.review.participants": "Participants",
  "bill.review.allocated": "Allocated",
  "bill.review.billTitle": "Bill title",
  "bill.review.destination": "Destination",
  "bill.review.destinationTag": "Destination Tag",
  "bill.review.notPresent": "Not present",
  "bill.review.network": "Network",
  "bill.review.asset": "Settlement Asset",
  "bill.review.assetType": "Asset type",
  "bill.review.issued": "Issued Asset",
  "bill.review.native": "Native XRP",
  "bill.review.issuer": "Official issuer",
  "bill.review.rule": "Allocation rule to freeze",
  "bill.review.ruleBody": "These calculation choices accompany the server-validated participant amounts shown below.",
  "bill.review.method": "Method",
  "bill.review.remainderUnits": "Remainder units",
  "bill.review.remainderAssignment": "Remainder assignment",
  "bill.review.participantAllocations": "Participant allocations",
  "bill.review.participantBody": "Each row becomes a separate immutable {asset} payment slot.",
  "bill.review.slot": "Payment slot {number}",
  "bill.review.final": "Final confirmation",
  "bill.review.finalBody": "No funds move when the Bill is created. The {asset} identity, destination, issuer, allocation result, amounts, payers, tags, and InvoiceIDs are frozen for every participant link.",
  "bill.review.feeNotice": "XRPL network fees remain payable separately in XRP.",
  "bill.review.back": "Back to edit",
  "bill.review.creating": "Freezing bill and slots",
  "bill.review.confirm": "Freeze bill and create payment links",
  "bill.created.badge": "Bill created",
  "bill.created.description": "The {asset} Bill is frozen. Save the creator progress link, then send each participant their payment link.",
  "bill.created.asset": "Settlement Asset",
  "bill.created.total": "Total",
  "bill.created.creatorShare": "Creator share",
  "bill.created.participants": "Participants",
  "bill.created.issuer": "Official RLUSD issuer",
  "bill.created.fee": "Participant wallets pay the XRPL network fee separately in XRP.",
  "bill.created.creatorProgress": "Creator progress",
  "bill.created.creatorProgressBody": "Shows participant labels, expected wallets, InvoiceIDs, and independent verification states.",
  "bill.created.copyCreator": "Copy creator progress link",
  "bill.created.readOnly": "Read-only progress",
  "bill.created.readOnlyBody": "Shows amounts and settlement states without participant labels, expected wallet addresses, or InvoiceIDs.",
  "bill.created.copyReadOnly": "Copy read-only progress link",
  "bill.created.paymentLinks": "Participant payment links",
  "bill.created.unnamed": "Unnamed participant",
  "bill.created.copied": "Copied",
  "bill.created.copyPayment": "Copy payment link",
  "bill.created.capabilityNotice": "Payment and progress capabilities stay in URL fragments. Share each capability only with its intended viewer.",
  "bill.created.another": "Create another bill",
  "roadmap.eyebrow": "Public status",
  "roadmap.title": "Roadmap",
  "roadmap.description": "This page separates usable product behavior from release-blocking work and later direction. An item moves to Available only after it is merged, tested, and usable in the intended environment.",
  "changelog.eyebrow": "Completed work",
  "changelog.title": "Changelog",
  "changelog.description": "Meaningful user-facing, security, compatibility, persistence, and operational changes. Planned work remains on the Roadmap.",
  "changelog.status.title": "Current release status",
  "changelog.status.body": "Mainnet remains halted and blocked pending a fresh controlled RLUSD ceremony and final release approval.",
} as const;

export type MessageKey = keyof typeof en;
export type MessageCatalog = Record<MessageKey, string>;

const ja: MessageCatalog = {
  "language.label": "言語",
  "language.english": "English",
  "language.japanese": "日本語",
  "language.korean": "한국어",
  "nav.roadmap": "ロードマップ",
  "nav.changelog": "更新履歴",
  "nav.source": "ソースコード",
  "nav.home": "ホーム",
  "home.eyebrow": "資金を預からない共同精算",
  "home.title": "費用を分けて、",
  "home.titleAccent": "直接精算。",
  "home.description": "XRPまたは公式RLUSDで共同請求を作成し、参加者ごとの支払額を固定して、XRPL {network}上の直接送金を検証します。",
  "home.halted": "管理された公開準備が完了するまで、Mainnetでの支払い作成は停止中です。画面は閲覧できますが、公開承認までは支払い要求を作成しません。",
  "home.cta.create": "{network}で請求を作成",
  "home.cta.status": "請求作成の状態を確認",
  "home.cta.docs": "製品仕様を読む",
  "home.principle.approve.title": "支払いは毎回本人が承認",
  "home.principle.approve.body": "参加者は自分のXamanウォレットで内容を確認し、署名します。",
  "home.principle.direct.title": "資金は直接移動",
  "home.principle.direct.body": "Group Payが中間受取人やアプリ内残高になることはありません。",
  "home.principle.verify.title": "台帳検証後に完了",
  "home.principle.verify.body": "検証済みトランザクションが一致するまで支払済みにはなりません。",
  "home.step.create.title": "作成",
  "home.step.create.body": "受取先、資産、合計額、参加者ごとの負担額を設定します。",
  "home.step.sign.title": "署名",
  "home.step.sign.body": "各参加者がXamanで自分の支払いを承認します。",
  "home.step.verify.title": "検証",
  "home.step.verify.body": "Group Payが検証済みトランザクションを確認して完了します。",
  "home.footer": "非カストディ型の調整と検証済み台帳による確認。",
  "bill.page.eyebrow": "作成者フロー · XRPL {network}",
  "bill.page.title": "請求を1つ作り、各参加者へ正確な負担額を送ります。",
  "bill.page.description": "Group Payは受取先、決済資産、配分を固定し、参加者ごとに別の支払いリンクを作成します。資金は参加者のウォレットから受取人へ直接送られます。",
  "bill.page.halted.title": "Mainnetでの請求作成はまだ一般公開されていません",
  "bill.page.halted.body": "管理された公開確認のため、この環境では操作を停止しています。この状態では支払い要求を作成できません。審査済みのMainnet公開設定が反映された場合にのみ自動的に有効になります。",
  "bill.page.releaseStatus": "公開状況を見る",
  "bill.page.completedWork": "完了した変更を見る",
  "bill.form.eyebrow": "共同請求",
  "bill.form.title": "請求で使用する決済資産を1つ選択",
  "bill.form.description": "全参加者がXRPL {network}上の同じ固定資産で支払います。確認画面で確定するまで支払い可能にはなりません。",
  "bill.form.reviewing": "請求内容を検証中",
  "bill.form.review": "固定前に請求内容を確認",
  "bill.form.error.review": "請求内容を確認できませんでした。",
  "bill.form.error.create": "共同請求を作成できませんでした。",
  "bill.asset.legend": "決済資産",
  "bill.asset.xrp": "XRPL {network}のネイティブXRP",
  "bill.asset.rlusd": "XRPL {network}で発行された公式Ripple USD",
  "bill.asset.issuer": "発行者 {issuer}",
  "bill.asset.rlusdNotice": "受取先アカウントは公式RLUSDを受け取れる状態である必要があります。発行者と金額は各参加者の支払い枠に固定されます。",
  "bill.field.title": "請求名",
  "bill.field.destination": "作成者の受取アドレス",
  "bill.field.total": "合計",
  "bill.field.creatorShare": "作成者の負担額",
  "bill.field.destinationTag": "Destination Tag",
  "bill.field.optional": "任意",
  "bill.allocation.method": "配分方法",
  "bill.allocation.description": "請求を固定する前に、サーバーが最終負担額を再計算します。",
  "bill.allocation.custom.label": "個別金額",
  "bill.allocation.custom.description": "参加者ごとの最終負担額を直接入力します。",
  "bill.allocation.equal.label": "均等",
  "bill.allocation.equal.description": "参加者分を均等に分けます。",
  "bill.allocation.percentage.label": "割合",
  "bill.allocation.percentage.description": "合計100%になる正確な割合を割り当てます。",
  "bill.allocation.shares.label": "比率",
  "bill.allocation.shares.description": "正の整数比を使用して配分します。",
  "bill.participants.title": "参加者",
  "bill.participants.minimum": "支払い枠は最低2件必要です。",
  "bill.participants.add": "参加者を追加",
  "bill.participant.number": "参加者 {number}",
  "bill.participant.remove": "参加者 {number} を削除",
  "bill.participant.label": "表示名",
  "bill.participant.payer": "支払予定アドレス",
  "bill.participant.amount": "負担額",
  "bill.participant.percentage": "割合",
  "bill.participant.shares": "比率",
  "bill.participant.calculated": "計算された負担額",
  "bill.remainder.title": "端数の割当先を明示",
  "bill.remainder.description.one": "計算後に最小単位が{units}残ります。Group Payが破棄したり自動で割り当てたりすることはありません。",
  "bill.remainder.description.many": "計算後に最小単位が{units}残ります。Group Payが破棄したり自動で割り当てたりすることはありません。",
  "bill.remainder.creator.label": "作成者が端数を負担",
  "bill.remainder.creator.description": "すべての端数を作成者の負担額へ加えます。",
  "bill.remainder.first.label": "最初の参加者が端数を負担",
  "bill.remainder.first.description": "すべての端数を参加者1へ加えます。",
  "bill.remainder.selected.label": "参加者を1人選択",
  "bill.remainder.selected.description": "すべての端数を選択した参加者へ加えます。",
  "bill.remainder.manual.label": "手動で配分",
  "bill.remainder.manual.description": "端数だけを参加者間で分配します。",
  "bill.remainder.participant": "端数を負担する参加者",
  "bill.remainder.select": "参加者を選択",
  "bill.remainder.manualTotal": "手動配分の合計は正確に{units}である必要があります。",
  "bill.remainder.unitsFor": "{participant}の端数単位",
  "bill.status.exact": "配分は一致しています",
  "bill.status.remainder": "端数の割当方法が必要です",
  "bill.status.incomplete": "配分が未完成です",
  "bill.status.enterAll": "合計額、作成者負担額、全参加者の金額を入力してください。",
  "bill.status.remaining": "残り{amount} {asset}を割り当てる必要があります。",
  "bill.status.over": "請求合計を{amount} {asset}超過しています。",
  "bill.status.matches": "作成者と参加者の負担額が{asset}の合計と一致しています。",
  "bill.review.badge": "{network}確認",
  "bill.review.exact": "配分一致",
  "bill.review.title": "固定前の最終確認",
  "bill.review.description": "受取先、支払者、資産、配分方法、金額をすべて確認してください。次の操作で条件が固定され、参加者ごとのリンクが作成されます。",
  "bill.review.mainnet.title": "実資産を動かすMainnet支払いリンク",
  "bill.review.mainnet.body": "参加者は実際のXRPまたはRLUSDを送るトランザクションへ署名します。固定前に受取先、支払者アドレス、資産、金額を確認してください。",
  "bill.review.billTotal": "請求合計",
  "bill.review.creatorShare": "作成者負担額",
  "bill.review.participants": "参加者数",
  "bill.review.allocated": "配分済み",
  "bill.review.billTitle": "請求名",
  "bill.review.destination": "受取先",
  "bill.review.destinationTag": "Destination Tag",
  "bill.review.notPresent": "なし",
  "bill.review.network": "ネットワーク",
  "bill.review.asset": "決済資産",
  "bill.review.assetType": "資産種別",
  "bill.review.issued": "発行資産",
  "bill.review.native": "ネイティブXRP",
  "bill.review.issuer": "公式発行者",
  "bill.review.rule": "固定する配分ルール",
  "bill.review.ruleBody": "以下のサーバー検証済み負担額とともに、この計算条件を記録します。",
  "bill.review.method": "方法",
  "bill.review.remainderUnits": "端数単位",
  "bill.review.remainderAssignment": "端数の割当先",
  "bill.review.participantAllocations": "参加者ごとの配分",
  "bill.review.participantBody": "各行が個別の固定{asset}支払い枠になります。",
  "bill.review.slot": "支払い枠 {number}",
  "bill.review.final": "最終確認",
  "bill.review.finalBody": "請求作成時には資金は移動しません。{asset}の識別情報、受取先、発行者、配分結果、金額、支払者、タグ、InvoiceIDが参加者リンクごとに固定されます。",
  "bill.review.feeNotice": "XRPLネットワーク手数料は別途XRPで必要です。",
  "bill.review.back": "編集へ戻る",
  "bill.review.creating": "請求と支払い枠を固定中",
  "bill.review.confirm": "請求を固定して支払いリンクを作成",
  "bill.created.badge": "請求を作成しました",
  "bill.created.description": "{asset}請求を固定しました。作成者用進捗リンクを保存し、各参加者へ支払いリンクを送ってください。",
  "bill.created.asset": "決済資産",
  "bill.created.total": "合計",
  "bill.created.creatorShare": "作成者負担額",
  "bill.created.participants": "参加者数",
  "bill.created.issuer": "公式RLUSD発行者",
  "bill.created.fee": "参加者のウォレットはXRPL手数料を別途XRPで支払います。",
  "bill.created.creatorProgress": "作成者用進捗",
  "bill.created.creatorProgressBody": "参加者名、支払予定ウォレット、InvoiceID、独立検証の状態を表示します。",
  "bill.created.copyCreator": "作成者用進捗リンクをコピー",
  "bill.created.readOnly": "閲覧専用進捗",
  "bill.created.readOnlyBody": "参加者名、支払予定アドレス、InvoiceIDを隠して金額と精算状態を表示します。",
  "bill.created.copyReadOnly": "閲覧専用進捗リンクをコピー",
  "bill.created.paymentLinks": "参加者用支払いリンク",
  "bill.created.unnamed": "名前未設定の参加者",
  "bill.created.copied": "コピーしました",
  "bill.created.copyPayment": "支払いリンクをコピー",
  "bill.created.capabilityNotice": "支払い・進捗権限はURLフラグメント内に保持されます。それぞれ意図した相手にだけ共有してください。",
  "bill.created.another": "別の請求を作成",
  "roadmap.eyebrow": "公開状況",
  "roadmap.title": "ロードマップ",
  "roadmap.description": "利用可能な機能、公開を止めている作業、将来構想を分けて表示します。対象環境で利用でき、実装・テスト済みになった項目だけを利用可能へ移します。",
  "changelog.eyebrow": "完了した変更",
  "changelog.title": "更新履歴",
  "changelog.description": "利用者向け機能、安全性、互換性、保存、運用に関する主要変更です。予定はロードマップに記載します。",
  "changelog.status.title": "現在の公開状況",
  "changelog.status.body": "Mainnetは、新しい管理下RLUSD試験と最終公開承認が完了するまで停止・保留状態です。",
};

const ko: MessageCatalog = {
  "language.label": "언어",
  "language.english": "English",
  "language.japanese": "日本語",
  "language.korean": "한국어",
  "nav.roadmap": "로드맵",
  "nav.changelog": "변경 기록",
  "nav.source": "소스",
  "nav.home": "홈",
  "home.eyebrow": "비수탁형 공동 정산",
  "home.title": "비용을 나누고,",
  "home.titleAccent": "직접 정산하세요.",
  "home.description": "XRP 또는 공식 RLUSD로 공동 청구서를 만들고 참가자별 의무 금액을 고정한 뒤 XRPL {network}의 직접 결제를 검증합니다.",
  "home.halted": "통제된 출시 점검이 끝날 때까지 Mainnet 결제 생성은 중지되어 있습니다. 화면은 볼 수 있지만 출시 승인 전에는 결제 요청을 만들지 않습니다.",
  "home.cta.create": "{network} 청구서 만들기",
  "home.cta.status": "청구서 생성 상태 보기",
  "home.cta.docs": "제품 기반 문서 읽기",
  "home.principle.approve.title": "모든 결제를 직접 승인",
  "home.principle.approve.body": "참가자는 자신의 Xaman 지갑에서 내용을 확인하고 서명합니다.",
  "home.principle.direct.title": "자금은 직접 이동",
  "home.principle.direct.body": "Group Pay는 중간 수취인이나 앱 잔액이 되지 않습니다.",
  "home.principle.verify.title": "원장 검증 후 완료",
  "home.principle.verify.body": "검증된 트랜잭션이 일치하기 전에는 결제 완료로 표시하지 않습니다.",
  "home.step.create.title": "생성",
  "home.step.create.body": "수취인, 자산, 합계 및 참가자별 부담액을 설정합니다.",
  "home.step.sign.title": "서명",
  "home.step.sign.body": "각 참가자가 Xaman에서 자신의 결제를 승인합니다.",
  "home.step.verify.title": "검증",
  "home.step.verify.body": "Group Pay가 검증된 트랜잭션을 확인한 뒤 완료합니다.",
  "home.footer": "비수탁형 조정과 검증된 원장 확인.",
  "bill.page.eyebrow": "생성자 흐름 · XRPL {network}",
  "bill.page.title": "청구서 하나를 만들고 각 참가자에게 정확한 부담액을 보내세요.",
  "bill.page.description": "Group Pay는 수취 주소, 결제 자산, 배분을 고정하고 참가자마다 별도의 결제 링크를 만듭니다. 자금은 참가자 지갑에서 수취인에게 직접 이동합니다.",
  "bill.page.halted.title": "Mainnet 청구서 생성은 아직 공개되지 않았습니다",
  "bill.page.halted.body": "통제된 출시 점검을 위해 이 배포는 운영이 중지되어 있습니다. 이 상태에서는 결제 요청을 만들 수 없습니다. 검토된 Mainnet 공개 설정이 배포된 경우에만 자동으로 활성화됩니다.",
  "bill.page.releaseStatus": "출시 상태 보기",
  "bill.page.completedWork": "완료된 작업 보기",
  "bill.form.eyebrow": "공동 청구서",
  "bill.form.title": "청구서의 결제 자산 하나를 선택하세요",
  "bill.form.description": "모든 참가자는 XRPL {network}에서 동일하게 고정된 자산으로 결제합니다. 검토 단계를 확인하기 전에는 결제할 수 없습니다.",
  "bill.form.reviewing": "청구서 검토 확인 중",
  "bill.form.review": "고정 전에 청구서 검토",
  "bill.form.error.review": "청구서를 검토할 수 없습니다.",
  "bill.form.error.create": "공동 청구서를 만들 수 없습니다.",
  "bill.asset.legend": "결제 자산",
  "bill.asset.xrp": "XRPL {network}의 네이티브 XRP",
  "bill.asset.rlusd": "XRPL {network}에서 발행된 공식 Ripple USD",
  "bill.asset.issuer": "발행자 {issuer}",
  "bill.asset.rlusdNotice": "수취 계정은 공식 RLUSD를 받을 수 있어야 합니다. 발행자와 금액은 모든 참가자 슬롯에 고정됩니다.",
  "bill.field.title": "청구서 제목",
  "bill.field.destination": "생성자 수취 주소",
  "bill.field.total": "합계",
  "bill.field.creatorShare": "생성자 부담액",
  "bill.field.destinationTag": "Destination Tag",
  "bill.field.optional": "선택 사항",
  "bill.allocation.method": "배분 방식",
  "bill.allocation.description": "청구서를 고정하기 전에 서버가 최종 의무 금액을 다시 계산합니다.",
  "bill.allocation.custom.label": "직접 금액",
  "bill.allocation.custom.description": "각 참가자의 최종 의무 금액을 직접 입력합니다.",
  "bill.allocation.equal.label": "균등",
  "bill.allocation.equal.description": "참가자 몫을 균등하게 나눕니다.",
  "bill.allocation.percentage.label": "백분율",
  "bill.allocation.percentage.description": "합계가 100%가 되도록 정확한 비율을 지정합니다.",
  "bill.allocation.shares.label": "지분",
  "bill.allocation.shares.description": "양의 정수 가중치로 배분합니다.",
  "bill.participants.title": "참가자",
  "bill.participants.minimum": "최소 두 개의 결제 슬롯이 필요합니다.",
  "bill.participants.add": "참가자 추가",
  "bill.participant.number": "참가자 {number}",
  "bill.participant.remove": "참가자 {number} 삭제",
  "bill.participant.label": "표시 이름",
  "bill.participant.payer": "예상 결제자 주소",
  "bill.participant.amount": "배정 금액",
  "bill.participant.percentage": "백분율",
  "bill.participant.shares": "지분",
  "bill.participant.calculated": "계산된 의무 금액",
  "bill.remainder.title": "나머지 단위를 명시적으로 배정",
  "bill.remainder.description.one": "계산 후 최소 자산 단위 {units}개가 남습니다. Group Pay는 이를 버리거나 자동으로 배정하지 않습니다.",
  "bill.remainder.description.many": "계산 후 최소 자산 단위 {units}개가 남습니다. Group Pay는 이를 버리거나 자동으로 배정하지 않습니다.",
  "bill.remainder.creator.label": "생성자가 나머지 부담",
  "bill.remainder.creator.description": "모든 나머지 단위를 생성자 부담액에 더합니다.",
  "bill.remainder.first.label": "첫 참가자가 나머지 부담",
  "bill.remainder.first.description": "모든 나머지 단위를 참가자 1에게 더합니다.",
  "bill.remainder.selected.label": "참가자 한 명 선택",
  "bill.remainder.selected.description": "모든 나머지 단위를 선택한 참가자에게 더합니다.",
  "bill.remainder.manual.label": "수동 배분",
  "bill.remainder.manual.description": "나머지 단위만 참가자 사이에 나눕니다.",
  "bill.remainder.participant": "나머지 참가자",
  "bill.remainder.select": "참가자 선택",
  "bill.remainder.manualTotal": "수동 나머지 증가분의 합계는 정확히 {units}여야 합니다.",
  "bill.remainder.unitsFor": "{participant}의 나머지 단위",
  "bill.status.exact": "배분 일치",
  "bill.status.remainder": "나머지 규칙 필요",
  "bill.status.incomplete": "배분 미완료",
  "bill.status.enterAll": "합계, 생성자 부담액, 모든 참가자 금액을 입력하세요.",
  "bill.status.remaining": "{amount} {asset}를 더 배정해야 합니다.",
  "bill.status.over": "청구서 합계보다 {amount} {asset} 많이 배정되었습니다.",
  "bill.status.matches": "생성자와 참가자 금액이 {asset} 합계와 일치합니다.",
  "bill.review.badge": "{network} 검토",
  "bill.review.exact": "배분 일치",
  "bill.review.title": "고정 전 최종 검토",
  "bill.review.description": "수취인, 결제자, 자산, 배분 규칙, 금액을 모두 확인하세요. 다음 단계에서 조건을 고정하고 참가자별 링크를 만듭니다.",
  "bill.review.mainnet.title": "실제 자산을 이동하는 Mainnet 결제 링크",
  "bill.review.mainnet.body": "참가자는 실제 XRP 또는 RLUSD를 이동하는 트랜잭션에 서명합니다. 고정 전에 수취인, 결제자 주소, 자산, 금액을 확인하세요.",
  "bill.review.billTotal": "청구서 합계",
  "bill.review.creatorShare": "생성자 부담액",
  "bill.review.participants": "참가자 수",
  "bill.review.allocated": "배분됨",
  "bill.review.billTitle": "청구서 제목",
  "bill.review.destination": "수취인",
  "bill.review.destinationTag": "Destination Tag",
  "bill.review.notPresent": "없음",
  "bill.review.network": "네트워크",
  "bill.review.asset": "결제 자산",
  "bill.review.assetType": "자산 유형",
  "bill.review.issued": "발행 자산",
  "bill.review.native": "네이티브 XRP",
  "bill.review.issuer": "공식 발행자",
  "bill.review.rule": "고정할 배분 규칙",
  "bill.review.ruleBody": "아래 서버 검증 참가자 금액과 함께 이 계산 조건을 기록합니다.",
  "bill.review.method": "방식",
  "bill.review.remainderUnits": "나머지 단위",
  "bill.review.remainderAssignment": "나머지 배정",
  "bill.review.participantAllocations": "참가자 배분",
  "bill.review.participantBody": "각 행은 별도의 고정 {asset} 결제 슬롯이 됩니다.",
  "bill.review.slot": "결제 슬롯 {number}",
  "bill.review.final": "최종 확인",
  "bill.review.finalBody": "청구서를 만들 때 자금은 이동하지 않습니다. {asset} 식별 정보, 수취인, 발행자, 배분 결과, 금액, 결제자, 태그, InvoiceID가 각 참가자 링크에 고정됩니다.",
  "bill.review.feeNotice": "XRPL 네트워크 수수료는 별도로 XRP로 지불해야 합니다.",
  "bill.review.back": "편집으로 돌아가기",
  "bill.review.creating": "청구서와 슬롯 고정 중",
  "bill.review.confirm": "청구서 고정 및 결제 링크 생성",
  "bill.created.badge": "청구서 생성 완료",
  "bill.created.description": "{asset} 청구서가 고정되었습니다. 생성자 진행 링크를 저장하고 각 참가자에게 결제 링크를 보내세요.",
  "bill.created.asset": "결제 자산",
  "bill.created.total": "합계",
  "bill.created.creatorShare": "생성자 부담액",
  "bill.created.participants": "참가자 수",
  "bill.created.issuer": "공식 RLUSD 발행자",
  "bill.created.fee": "참가자 지갑은 XRPL 네트워크 수수료를 별도로 XRP로 지불합니다.",
  "bill.created.creatorProgress": "생성자 진행 상황",
  "bill.created.creatorProgressBody": "참가자 이름, 예상 지갑, InvoiceID, 독립 검증 상태를 표시합니다.",
  "bill.created.copyCreator": "생성자 진행 링크 복사",
  "bill.created.readOnly": "읽기 전용 진행 상황",
  "bill.created.readOnlyBody": "참가자 이름, 예상 지갑 주소, InvoiceID 없이 금액과 정산 상태를 표시합니다.",
  "bill.created.copyReadOnly": "읽기 전용 진행 링크 복사",
  "bill.created.paymentLinks": "참가자 결제 링크",
  "bill.created.unnamed": "이름 없는 참가자",
  "bill.created.copied": "복사됨",
  "bill.created.copyPayment": "결제 링크 복사",
  "bill.created.capabilityNotice": "결제 및 진행 권한은 URL 프래그먼트에 유지됩니다. 각 권한은 의도한 사람에게만 공유하세요.",
  "bill.created.another": "다른 청구서 만들기",
  "roadmap.eyebrow": "공개 상태",
  "roadmap.title": "로드맵",
  "roadmap.description": "사용 가능한 기능, 출시 차단 작업, 이후 방향을 구분합니다. 의도한 환경에서 실제로 사용할 수 있고 구현과 테스트가 끝난 항목만 사용 가능으로 이동합니다.",
  "changelog.eyebrow": "완료된 작업",
  "changelog.title": "변경 기록",
  "changelog.description": "사용자 기능, 보안, 호환성, 저장, 운영과 관련된 주요 변경입니다. 계획된 작업은 로드맵에 남깁니다.",
  "changelog.status.title": "현재 출시 상태",
  "changelog.status.body": "새로운 통제된 RLUSD 테스트와 최종 출시 승인이 완료될 때까지 Mainnet은 중지 및 차단 상태입니다.",
};

export const CATALOGS: Record<Locale, MessageCatalog> = { en, ja, ko };

export function isLocale(value: string | null | undefined): value is Locale {
  return SUPPORTED_LOCALES.includes(value as Locale);
}

export function normalizeLocale(value: string | null | undefined): Locale {
  if (!value) return "en";
  const normalized = value.trim().toLowerCase().split(/[-_]/)[0];
  return isLocale(normalized) ? normalized : "en";
}

export function resolveLocale(input: {
  cookie?: string | null;
  acceptLanguage?: string | null;
}): Locale {
  if (isLocale(input.cookie)) return input.cookie;
  const preferred = input.acceptLanguage
    ?.split(",")
    .map((item) => item.split(";")[0]?.trim())
    .find((item) => isLocale(normalizeLocale(item)));
  return normalizeLocale(preferred);
}

export function translate(
  locale: Locale,
  key: MessageKey,
  variables: Record<string, string | number> = {},
): string {
  const template = CATALOGS[locale][key] ?? CATALOGS.en[key];
  return template.replace(/\{([A-Za-z0-9_]+)\}/g, (_, name: string) =>
    Object.prototype.hasOwnProperty.call(variables, name)
      ? String(variables[name])
      : `{${name}}`,
  );
}
