import type { Locale } from "./catalog";
import { useLocalization } from "./provider";

const en = {
  "payer.page.eyebrow": "Participant flow",
  "payer.page.title": "Review your share. Approve the exact payment in Xaman.",
  "payer.page.description": "This page reads the private capability from the shared link, loads the frozen {network} payment slot, and verifies the submitted transaction on a validated XRP Ledger before marking it paid.",
  "payer.link.loading": "Loading payment link",
  "payer.link.unavailable": "Payment link unavailable",
  "payer.link.invalid": "This link is incomplete or invalid. Ask the bill creator for a new participant payment link.",
  "payer.details.loading": "Loading frozen payment details",
  "payer.details.completed": "Payment already completed",
  "payer.details.unavailable": "Payment link unavailable",
  "payer.tryAgain": "Try again",
  "payer.summary.eyebrow": "Participant payment",
  "payer.summary.share": "Your share",
  "payer.summary.officialRlusd": "Official RLUSD on XRPL {network}",
  "payer.summary.participant": "Participant",
  "payer.summary.asset": "Settlement Asset",
  "payer.summary.issuer": "Official issuer",
  "payer.summary.recipient": "Recipient",
  "payer.summary.expectedWallet": "Expected wallet",
  "payer.summary.destinationTag": "Destination Tag",
  "payer.summary.notPresent": "Not present",
  "payer.summary.frozen": "These values are frozen by the private payment capability. Group Pay cannot edit them and never receives the settlement funds.",
  "payer.summary.fee": "The XRPL network fee is paid separately in XRP.",
  "payer.confirm.eyebrow": "Final confirmation",
  "payer.confirm.title": "Confirm the exact {network} payment",
  "payer.confirm.body": "Group Pay will create a short-lived Sign Request containing these immutable fields. You must still inspect and approve it in Xaman.",
  "payer.confirm.amount": "Amount",
  "payer.confirm.network": "Network",
  "payer.confirm.asset": "Settlement Asset",
  "payer.confirm.feeAsset": "Network fee asset",
  "payer.confirm.issuer": "Official issuer",
  "payer.confirm.destination": "Destination",
  "payer.confirm.signer": "Expected signer",
  "payer.confirm.destinationTag": "Destination Tag",
  "payer.confirm.sourceTag": "Source Tag",
  "payer.confirm.noFunds": "No funds move at this step.",
  "payer.confirm.direct": "{asset} moves directly to the recipient only after you approve the exact transaction in Xaman.",
  "payer.confirm.fee": "The wallet also pays the XRPL network fee in XRP.",
  "payer.confirm.back": "Back to details",
  "payer.confirm.create": "Create Xaman Sign Request",
  "payer.waiting.title": "Waiting for approval in Xaman",
  "payer.waiting.body": "Compare the transaction in your wallet with the confirmed details before signing.",
  "payer.waiting.qrAlt": "QR code to open this Xaman sign request",
  "payer.waiting.open": "Open securely in Xaman",
  "payer.waiting.check": "Check status",
  "payer.ready.title": "Frozen payment details loaded",
  "payer.ready.body": "Review the exact {network} payment once more before Group Pay creates a short-lived Xaman Sign Request.",
  "payer.ready.review": "Review final payment",
  "payer.state.preparing.title": "Preparing secure request",
  "payer.state.preparing.body": "The confirmed frozen conditions are being placed into a short-lived {network} Xaman Sign Request.",
  "payer.state.verifying.title": "Verifying on the XRP Ledger",
  "payer.state.verifying.body": "The submitted transaction must appear in a validated {network} ledger and match every frozen slot condition.",
  "payer.state.pending.title": "Ledger confirmation pending",
  "payer.state.checkAgain": "Check again",
  "payer.state.verified.title": "Ledger verified",
  "payer.state.verified.body": "{amount} {asset} was delivered directly to the recipient and the payment slot is now marked paid.",
  "payer.state.receiptExisting": "This exact transaction was already recorded safely.",
  "payer.state.receiptRecorded": "A durable verification receipt was recorded.",
  "payer.state.failed.title": "Payment could not be verified",
  "payer.state.rejected.title": "Request rejected",
  "payer.state.rejected.body": "No settlement payment was submitted. Review the frozen details again before creating another short-lived request.",
  "payer.state.rejected.action": "Review and try again",
  "payer.state.expired.title": "Request expired",
  "payer.state.expired.body": "No settlement payment was submitted. Review the frozen details again before creating a fresh Xaman request.",
  "payer.state.expired.action": "Review and create new request",
  "payer.error.request": "The payment request could not be completed.",
  "payer.error.details": "The frozen payment details could not be loaded.",
  "payer.error.mismatch": "The verified response did not match the frozen participant payment details.",
  "payer.error.ledger": "The validated ledger could not be checked.",
  "payer.error.create": "The payment request could not be created.",
  "payer.error.status": "The Xaman status could not be checked.",
} as const;

export type CriticalMessageKey = keyof typeof en;
type CriticalCatalog = Record<CriticalMessageKey, string>;

const ja: CriticalCatalog = {
  "payer.page.eyebrow": "参加者フロー",
  "payer.page.title": "自分の負担額を確認し、Xamanで正確な支払いを承認します。",
  "payer.page.description": "共有リンク内の非公開権限から固定済み{network}支払い枠を読み込み、送信されたトランザクションを検証済みXRP Ledgerで確認してから支払済みにします。",
  "payer.link.loading": "支払いリンクを読み込み中",
  "payer.link.unavailable": "支払いリンクを利用できません",
  "payer.link.invalid": "リンクが不完全または無効です。請求作成者から新しい参加者用支払いリンクを受け取ってください。",
  "payer.details.loading": "固定済み支払い内容を読み込み中",
  "payer.details.completed": "支払いは完了済みです",
  "payer.details.unavailable": "支払いリンクを利用できません",
  "payer.tryAgain": "再試行",
  "payer.summary.eyebrow": "参加者の支払い",
  "payer.summary.share": "あなたの負担額",
  "payer.summary.officialRlusd": "XRPL {network}の公式RLUSD",
  "payer.summary.participant": "参加者",
  "payer.summary.asset": "決済資産",
  "payer.summary.issuer": "公式発行者",
  "payer.summary.recipient": "受取人",
  "payer.summary.expectedWallet": "支払予定ウォレット",
  "payer.summary.destinationTag": "Destination Tag",
  "payer.summary.notPresent": "なし",
  "payer.summary.frozen": "これらの値は非公開支払い権限によって固定されています。Group Payは変更できず、精算資金を受け取ることもありません。",
  "payer.summary.fee": "XRPLネットワーク手数料は別途XRPで支払います。",
  "payer.confirm.eyebrow": "最終確認",
  "payer.confirm.title": "正確な{network}支払いを確認",
  "payer.confirm.body": "Group Payは以下の固定項目を含む短時間有効な署名要求を作成します。Xamanでも内容を確認して本人が承認する必要があります。",
  "payer.confirm.amount": "金額",
  "payer.confirm.network": "ネットワーク",
  "payer.confirm.asset": "決済資産",
  "payer.confirm.feeAsset": "手数料資産",
  "payer.confirm.issuer": "公式発行者",
  "payer.confirm.destination": "送金先",
  "payer.confirm.signer": "署名予定者",
  "payer.confirm.destinationTag": "Destination Tag",
  "payer.confirm.sourceTag": "Source Tag",
  "payer.confirm.noFunds": "この段階では資金は移動しません。",
  "payer.confirm.direct": "Xamanで正確なトランザクションを承認した場合にのみ、{asset}が受取人へ直接送られます。",
  "payer.confirm.fee": "ウォレットはXRPLネットワーク手数料もXRPで支払います。",
  "payer.confirm.back": "内容へ戻る",
  "payer.confirm.create": "Xaman署名要求を作成",
  "payer.waiting.title": "Xamanでの承認を待っています",
  "payer.waiting.body": "署名前に、ウォレット内のトランザクションと確認済み内容を比較してください。",
  "payer.waiting.qrAlt": "Xaman署名要求を開くQRコード",
  "payer.waiting.open": "Xamanで安全に開く",
  "payer.waiting.check": "状態を確認",
  "payer.ready.title": "固定済み支払い内容を読み込みました",
  "payer.ready.body": "Group Payが短時間有効なXaman署名要求を作成する前に、正確な{network}支払いをもう一度確認してください。",
  "payer.ready.review": "最終支払い内容を確認",
  "payer.state.preparing.title": "安全な要求を準備中",
  "payer.state.preparing.body": "確認済みの固定条件を短時間有効な{network} Xaman署名要求へ設定しています。",
  "payer.state.verifying.title": "XRP Ledgerで検証中",
  "payer.state.verifying.body": "送信済みトランザクションが検証済み{network}台帳に存在し、固定された全条件と一致する必要があります。",
  "payer.state.pending.title": "台帳確定待ち",
  "payer.state.checkAgain": "再確認",
  "payer.state.verified.title": "台帳検証完了",
  "payer.state.verified.body": "{amount} {asset}が受取人へ直接届き、この支払い枠を支払済みにしました。",
  "payer.state.receiptExisting": "このトランザクションはすでに安全に記録されています。",
  "payer.state.receiptRecorded": "永続的な検証レシートを記録しました。",
  "payer.state.failed.title": "支払いを検証できませんでした",
  "payer.state.rejected.title": "要求が拒否されました",
  "payer.state.rejected.body": "精算支払いは送信されていません。新しい短時間要求を作る前に固定内容をもう一度確認してください。",
  "payer.state.rejected.action": "確認して再試行",
  "payer.state.expired.title": "要求の期限が切れました",
  "payer.state.expired.body": "精算支払いは送信されていません。新しいXaman要求を作る前に固定内容をもう一度確認してください。",
  "payer.state.expired.action": "確認して新しい要求を作成",
  "payer.error.request": "支払い要求を完了できませんでした。",
  "payer.error.details": "固定済み支払い内容を読み込めませんでした。",
  "payer.error.mismatch": "検証結果が固定された参加者支払い内容と一致しませんでした。",
  "payer.error.ledger": "検証済み台帳を確認できませんでした。",
  "payer.error.create": "支払い要求を作成できませんでした。",
  "payer.error.status": "Xamanの状態を確認できませんでした。",
};

const ko: CriticalCatalog = {
  "payer.page.eyebrow": "참가자 흐름",
  "payer.page.title": "내 부담액을 확인하고 Xaman에서 정확한 결제를 승인하세요.",
  "payer.page.description": "공유 링크의 비공개 권한에서 고정된 {network} 결제 슬롯을 불러오고, 제출된 트랜잭션을 검증된 XRP Ledger에서 확인한 뒤 결제 완료로 표시합니다.",
  "payer.link.loading": "결제 링크 불러오는 중",
  "payer.link.unavailable": "결제 링크를 사용할 수 없습니다",
  "payer.link.invalid": "링크가 불완전하거나 유효하지 않습니다. 청구서 생성자에게 새 참가자 결제 링크를 요청하세요.",
  "payer.details.loading": "고정 결제 정보 불러오는 중",
  "payer.details.completed": "결제가 이미 완료되었습니다",
  "payer.details.unavailable": "결제 링크를 사용할 수 없습니다",
  "payer.tryAgain": "다시 시도",
  "payer.summary.eyebrow": "참가자 결제",
  "payer.summary.share": "내 부담액",
  "payer.summary.officialRlusd": "XRPL {network}의 공식 RLUSD",
  "payer.summary.participant": "참가자",
  "payer.summary.asset": "결제 자산",
  "payer.summary.issuer": "공식 발행자",
  "payer.summary.recipient": "수취인",
  "payer.summary.expectedWallet": "예상 지갑",
  "payer.summary.destinationTag": "Destination Tag",
  "payer.summary.notPresent": "없음",
  "payer.summary.frozen": "이 값들은 비공개 결제 권한으로 고정되어 있습니다. Group Pay는 이를 수정할 수 없으며 정산 자금을 받지 않습니다.",
  "payer.summary.fee": "XRPL 네트워크 수수료는 별도로 XRP로 지불합니다.",
  "payer.confirm.eyebrow": "최종 확인",
  "payer.confirm.title": "정확한 {network} 결제 확인",
  "payer.confirm.body": "Group Pay는 아래의 변경 불가능한 항목이 포함된 짧은 유효기간의 서명 요청을 만듭니다. Xaman에서도 내용을 확인하고 직접 승인해야 합니다.",
  "payer.confirm.amount": "금액",
  "payer.confirm.network": "네트워크",
  "payer.confirm.asset": "결제 자산",
  "payer.confirm.feeAsset": "수수료 자산",
  "payer.confirm.issuer": "공식 발행자",
  "payer.confirm.destination": "목적지",
  "payer.confirm.signer": "예상 서명자",
  "payer.confirm.destinationTag": "Destination Tag",
  "payer.confirm.sourceTag": "Source Tag",
  "payer.confirm.noFunds": "이 단계에서는 자금이 이동하지 않습니다.",
  "payer.confirm.direct": "Xaman에서 정확한 트랜잭션을 승인한 경우에만 {asset}가 수취인에게 직접 이동합니다.",
  "payer.confirm.fee": "지갑은 XRPL 네트워크 수수료도 XRP로 지불합니다.",
  "payer.confirm.back": "정보로 돌아가기",
  "payer.confirm.create": "Xaman 서명 요청 만들기",
  "payer.waiting.title": "Xaman 승인 대기 중",
  "payer.waiting.body": "서명하기 전에 지갑의 트랜잭션과 확인된 정보를 비교하세요.",
  "payer.waiting.qrAlt": "Xaman 서명 요청을 여는 QR 코드",
  "payer.waiting.open": "Xaman에서 안전하게 열기",
  "payer.waiting.check": "상태 확인",
  "payer.ready.title": "고정 결제 정보를 불러왔습니다",
  "payer.ready.body": "Group Pay가 짧은 유효기간의 Xaman 서명 요청을 만들기 전에 정확한 {network} 결제를 다시 확인하세요.",
  "payer.ready.review": "최종 결제 검토",
  "payer.state.preparing.title": "안전한 요청 준비 중",
  "payer.state.preparing.body": "확인된 고정 조건을 짧은 유효기간의 {network} Xaman 서명 요청에 넣고 있습니다.",
  "payer.state.verifying.title": "XRP Ledger에서 검증 중",
  "payer.state.verifying.body": "제출된 트랜잭션이 검증된 {network} 원장에 나타나고 고정된 모든 슬롯 조건과 일치해야 합니다.",
  "payer.state.pending.title": "원장 확정 대기 중",
  "payer.state.checkAgain": "다시 확인",
  "payer.state.verified.title": "원장 검증 완료",
  "payer.state.verified.body": "{amount} {asset}가 수취인에게 직접 전달되었고 결제 슬롯이 완료로 표시되었습니다.",
  "payer.state.receiptExisting": "이 트랜잭션은 이미 안전하게 기록되었습니다.",
  "payer.state.receiptRecorded": "영구 검증 영수증을 기록했습니다.",
  "payer.state.failed.title": "결제를 검증할 수 없습니다",
  "payer.state.rejected.title": "요청이 거부되었습니다",
  "payer.state.rejected.body": "정산 결제는 제출되지 않았습니다. 다른 짧은 유효기간의 요청을 만들기 전에 고정 정보를 다시 확인하세요.",
  "payer.state.rejected.action": "검토 후 다시 시도",
  "payer.state.expired.title": "요청이 만료되었습니다",
  "payer.state.expired.body": "정산 결제는 제출되지 않았습니다. 새 Xaman 요청을 만들기 전에 고정 정보를 다시 확인하세요.",
  "payer.state.expired.action": "검토 후 새 요청 만들기",
  "payer.error.request": "결제 요청을 완료할 수 없습니다.",
  "payer.error.details": "고정 결제 정보를 불러올 수 없습니다.",
  "payer.error.mismatch": "검증 응답이 고정된 참가자 결제 정보와 일치하지 않습니다.",
  "payer.error.ledger": "검증된 원장을 확인할 수 없습니다.",
  "payer.error.create": "결제 요청을 만들 수 없습니다.",
  "payer.error.status": "Xaman 상태를 확인할 수 없습니다.",
};

const catalogs: Record<Locale, CriticalCatalog> = { en, ja, ko };

export function criticalTranslate(
  locale: Locale,
  key: CriticalMessageKey,
  variables: Record<string, string | number> = {},
) {
  return catalogs[locale][key].replace(/\{([A-Za-z0-9_]+)\}/g, (_, name: string) =>
    Object.prototype.hasOwnProperty.call(variables, name)
      ? String(variables[name])
      : `{${name}}`,
  );
}

export function useCriticalLocalization() {
  const { locale } = useLocalization();
  return {
    locale,
    ct: (
      key: CriticalMessageKey,
      variables?: Record<string, string | number>,
    ) => criticalTranslate(locale, key, variables),
  };
}
