import type { Locale } from "./catalog";

const copy = {
  en: {
    retry_safe_title: "A new attempt is available",
    retry_safe_body: "The previous wallet request is no longer active. Group Pay will reconcile validated XRPL history before it creates a replacement request.",
    retry_safe_action: "Review and create a new request",
    wait_recheck_title: "Wait and check the same payment",
    wait_recheck_body: "Submission or ledger status is still uncertain. Do not create or sign a second payment while Group Pay checks the same attempt.",
    wait_recheck_action: "Check the same attempt again",
    setup_required_title: "Wallet setup or balance action is required",
    setup_required_body: "A confirmed readiness condition blocks payment creation. Resolve the displayed trust-line, asset-balance, XRP-fee, or reserve requirement, then recheck readiness.",
    setup_required_action: "Return to readiness checks",
    review_required_title: "This payment needs review",
    review_required_body: "A transaction may have moved value but did not safely satisfy the frozen PaymentSlot, or more than one candidate was found. Do not pay again until the Bill operator reviews it.",
    already_paid_title: "Payment already completed",
    already_paid_body: "A validated transaction already satisfies this PaymentSlot. No new wallet request can be created.",
    terminal_title: "No new payment is available",
    terminal_body: "This PaymentSlot is closed, unavailable, or cannot safely accept another request.",
    no_retry: "A replacement payment is blocked in this state.",
    reconcile: "Before retry, Group Pay checks the payer account and frozen InvoiceID for an existing validated payment.",
    technical: "Technical details",
    code: "Recovery code",
    diagnostic: "Diagnostic code",
    transaction: "Transaction ID",
    checkAgain: "Check again",
    retry: "Retry safely",
    returnReadiness: "Recheck wallet readiness",
  },
  ja: {
    retry_safe_title: "新しい試行を開始できます",
    retry_safe_body: "前のウォレット要求は有効ではありません。代替要求を作成する前に、Group Payが検証済みXRPL履歴を照合します。",
    retry_safe_action: "確認して新しい要求を作成",
    wait_recheck_title: "同じ支払いを待って再確認してください",
    wait_recheck_body: "送信または台帳状態がまだ確定していません。同じ試行を確認している間は、2件目の支払いを作成・署名しないでください。",
    wait_recheck_action: "同じ試行を再確認",
    setup_required_title: "ウォレットの準備または残高対応が必要です",
    setup_required_body: "確認済みの準備条件により支払い作成が止まっています。表示されたトラストライン、資産残高、XRP手数料、リザーブ条件を解消して再確認してください。",
    setup_required_action: "準備状態の確認へ戻る",
    review_required_title: "この支払いは確認が必要です",
    review_required_body: "資金が移動した可能性がある一方で固定済み支払枠を安全に満たしていないか、複数候補が見つかりました。請求の操作担当が確認するまで再支払いしないでください。",
    already_paid_title: "支払いは完了済みです",
    already_paid_body: "検証済みトランザクションがすでにこの支払枠を満たしています。新しいウォレット要求は作成できません。",
    terminal_title: "新しい支払いは利用できません",
    terminal_body: "この支払枠は終了済み、利用不能、または別の要求を安全に受け付けられない状態です。",
    no_retry: "この状態では代替支払いを作成できません。",
    reconcile: "再試行前に、Group Payは支払者アカウントと固定済みInvoiceIDから既存の検証済み支払いを確認します。",
    technical: "技術情報",
    code: "復旧コード",
    diagnostic: "診断コード",
    transaction: "トランザクションID",
    checkAgain: "再確認",
    retry: "安全に再試行",
    returnReadiness: "ウォレット準備状態を再確認",
  },
  ko: {
    retry_safe_title: "새 시도를 시작할 수 있습니다",
    retry_safe_body: "이전 지갑 요청은 더 이상 활성 상태가 아닙니다. Group Pay는 교체 요청을 만들기 전에 검증된 XRPL 기록을 대조합니다.",
    retry_safe_action: "검토 후 새 요청 만들기",
    wait_recheck_title: "같은 결제를 기다리고 다시 확인하십시오",
    wait_recheck_body: "제출 또는 원장 상태가 아직 확정되지 않았습니다. 같은 시도를 확인하는 동안 두 번째 결제를 만들거나 서명하지 마십시오.",
    wait_recheck_action: "같은 시도 다시 확인",
    setup_required_title: "지갑 설정 또는 잔액 조치가 필요합니다",
    setup_required_body: "확인된 준비 조건 때문에 결제 요청을 만들 수 없습니다. 표시된 트러스트라인, 자산 잔액, XRP 수수료 또는 준비금 조건을 해결한 뒤 다시 확인하십시오.",
    setup_required_action: "준비 상태 확인으로 돌아가기",
    review_required_title: "이 결제는 검토가 필요합니다",
    review_required_body: "가치가 이동했을 수 있지만 고정 PaymentSlot을 안전하게 충족하지 않았거나 여러 후보가 발견되었습니다. 청구 운영자가 검토할 때까지 다시 결제하지 마십시오.",
    already_paid_title: "결제가 이미 완료되었습니다",
    already_paid_body: "검증된 거래가 이미 이 PaymentSlot을 충족합니다. 새 지갑 요청을 만들 수 없습니다.",
    terminal_title: "새 결제를 사용할 수 없습니다",
    terminal_body: "이 PaymentSlot은 닫혔거나 사용할 수 없거나 다른 요청을 안전하게 받을 수 없는 상태입니다.",
    no_retry: "이 상태에서는 교체 결제가 차단됩니다.",
    reconcile: "재시도 전에 Group Pay는 결제자 계정과 고정 InvoiceID에서 기존 검증 결제를 확인합니다.",
    technical: "기술 세부 정보",
    code: "복구 코드",
    diagnostic: "진단 코드",
    transaction: "트랜잭션 ID",
    checkAgain: "다시 확인",
    retry: "안전하게 재시도",
    returnReadiness: "지갑 준비 상태 다시 확인",
  },
} as const;

export type PayerLifecycleMessageKey = keyof (typeof copy)["en"];

export function payerLifecycleTranslate(
  locale: Locale,
  key: PayerLifecycleMessageKey,
) {
  return copy[locale]?.[key] ?? copy.en[key];
}
