import type { Locale } from "./catalog";
import { useLocalization } from "./provider";

const catalogs = {
  en: {
    pageEyebrow: "Bill progress",
    pageTitle: "Track settlement without trusting wallet status alone.",
    pageBody: "Each slot changes only after the submitted transaction is independently verified on a validated XRP Ledger.",
    loading: "Loading bill progress",
    linkUnavailable: "Bill progress link unavailable",
    invalidLink: "This link is incomplete or invalid. Ask the bill creator for a new progress link.",
    unavailable: "Bill progress unavailable",
    fallback: "The bill progress could not be loaded.",
    retry: "Try again",
    creatorView: "Creator view",
    readOnlyView: "Read-only view",
    exactPayment: "Each slot updates only after its exact {asset} Payment is verified on a validated XRP Ledger.",
    issuer: "Official issuer {issuer}",
    refresh: "Refresh",
    progress: "Settlement progress",
    paidCount: "{paid}/{total} paid",
    billTotal: "Bill total",
    verified: "Verified externally",
    pending: "Pending slots",
    review: "Needs review",
    complete: "Settlement complete",
    completeBody: "All externally payable slots have a durable verified receipt.",
    slots: "Participant slots",
    adminBody: "Creator details are visible because this is the management capability.",
    publicBody: "Participant labels and expected wallet addresses are hidden in the read-only view.",
    participant: "Participant {number}",
    paymentSlot: "Payment slot {number}",
    expectedWallet: "Expected wallet {wallet}",
    verifiedTx: "Verified transaction {transaction}",
    publicProof: "View public proof",
    paid: "Paid",
    needsReview: "Needs review",
    verificationFailed: "Verification failed",
    submitted: "Submitted",
    validating: "Validating",
    awaitingSignature: "Awaiting signature",
    rejected: "Rejected",
    expired: "Request expired",
    unpaid: "Unpaid",
  },
  ja: {
    pageEyebrow: "請求の進捗",
    pageTitle: "ウォレット状態だけに頼らず精算状況を確認します。",
    pageBody: "各支払い枠は、送信済みトランザクションが検証済みXRP Ledgerで独立確認された場合にのみ更新されます。",
    loading: "請求の進捗を読み込み中",
    linkUnavailable: "請求進捗リンクを利用できません",
    invalidLink: "リンクが不完全または無効です。請求作成者から新しい進捗リンクを受け取ってください。",
    unavailable: "請求の進捗を利用できません",
    fallback: "請求の進捗を読み込めませんでした。",
    retry: "再試行",
    creatorView: "作成者表示",
    readOnlyView: "閲覧専用表示",
    exactPayment: "各支払い枠は、正確な{asset} Paymentが検証済みXRP Ledgerで確認された場合にのみ更新されます。",
    issuer: "公式発行者 {issuer}",
    refresh: "更新",
    progress: "精算進捗",
    paidCount: "{paid}/{total} 支払済み",
    billTotal: "請求合計",
    verified: "外部検証済み",
    pending: "未完了の支払い枠",
    review: "要確認",
    complete: "精算完了",
    completeBody: "外部支払い対象の全枠に永続的な検証レシートがあります。",
    slots: "参加者の支払い枠",
    adminBody: "管理権限を使用しているため、作成者向けの詳細を表示しています。",
    publicBody: "閲覧専用表示では参加者名と支払予定ウォレットを非表示にしています。",
    participant: "参加者 {number}",
    paymentSlot: "支払い枠 {number}",
    expectedWallet: "支払予定ウォレット {wallet}",
    verifiedTx: "検証済みトランザクション {transaction}",
    publicProof: "公開証明を見る",
    paid: "支払済み",
    needsReview: "要確認",
    verificationFailed: "検証失敗",
    submitted: "送信済み",
    validating: "検証中",
    awaitingSignature: "署名待ち",
    rejected: "拒否済み",
    expired: "要求期限切れ",
    unpaid: "未払い",
  },
  ko: {
    pageEyebrow: "청구서 진행 상황",
    pageTitle: "지갑 상태만 신뢰하지 않고 정산을 추적하세요.",
    pageBody: "각 슬롯은 제출된 트랜잭션이 검증된 XRP Ledger에서 독립적으로 확인된 후에만 변경됩니다.",
    loading: "청구서 진행 상황 불러오는 중",
    linkUnavailable: "청구서 진행 링크를 사용할 수 없습니다",
    invalidLink: "링크가 불완전하거나 유효하지 않습니다. 청구서 생성자에게 새 진행 링크를 요청하세요.",
    unavailable: "청구서 진행 상황을 사용할 수 없습니다",
    fallback: "청구서 진행 상황을 불러올 수 없습니다.",
    retry: "다시 시도",
    creatorView: "생성자 보기",
    readOnlyView: "읽기 전용 보기",
    exactPayment: "각 슬롯은 정확한 {asset} Payment가 검증된 XRP Ledger에서 확인된 후에만 업데이트됩니다.",
    issuer: "공식 발행자 {issuer}",
    refresh: "새로고침",
    progress: "정산 진행률",
    paidCount: "{paid}/{total} 결제 완료",
    billTotal: "청구서 합계",
    verified: "외부 검증 완료",
    pending: "대기 슬롯",
    review: "검토 필요",
    complete: "정산 완료",
    completeBody: "외부 결제 대상인 모든 슬롯에 영구 검증 영수증이 있습니다.",
    slots: "참가자 슬롯",
    adminBody: "관리 권한을 사용 중이므로 생성자 세부 정보가 표시됩니다.",
    publicBody: "읽기 전용 보기에서는 참가자 이름과 예상 지갑 주소를 숨깁니다.",
    participant: "참가자 {number}",
    paymentSlot: "결제 슬롯 {number}",
    expectedWallet: "예상 지갑 {wallet}",
    verifiedTx: "검증된 트랜잭션 {transaction}",
    publicProof: "공개 증명 보기",
    paid: "결제 완료",
    needsReview: "검토 필요",
    verificationFailed: "검증 실패",
    submitted: "제출됨",
    validating: "검증 중",
    awaitingSignature: "서명 대기",
    rejected: "거부됨",
    expired: "요청 만료",
    unpaid: "미결제",
  },
} as const;

export type ProgressMessageKey = keyof typeof catalogs.en;

export function progressTranslate(locale: Locale, key: ProgressMessageKey, variables: Record<string, string | number> = {}) {
  return catalogs[locale][key].replace(/\{([A-Za-z0-9_]+)\}/g, (_, name: string) => Object.prototype.hasOwnProperty.call(variables, name) ? String(variables[name]) : `{${name}}`);
}

export function useProgressLocalization() {
  const { locale } = useLocalization();
  return { gt: (key: ProgressMessageKey, variables?: Record<string, string | number>) => progressTranslate(locale, key, variables) };
}
