import type { Locale } from "./catalog";
import { useLocalization } from "./provider";

const catalogs = {
  en: {
    loading: "Loading transaction proof",
    unavailable: "Transaction proof unavailable",
    invalid: "This proof link is incomplete or invalid. Ask for a new verified-payment link.",
    fallback: "The transaction proof could not be loaded.",
    retry: "Try again",
    privacy: "Proof pages contain public ledger facts, not private bill details.",
    verified: "Ledger verified",
    delivered: "{amount} XRP delivered",
    summary: "This receipt records a successful XRP Payment observed on a validated ledger. It contains public transaction facts only.",
    validation: "Validation",
    validated: "Validated",
    result: "Result",
    ledger: "Ledger index",
    facts: "Verified transaction facts",
    factsBody: "Bill titles, participant labels, expected pre-payment data, operational timestamps, and Xaman payload identifiers are not included.",
    transaction: "Transaction ID",
    invoice: "InvoiceID",
    sender: "Sender",
    destination: "Destination",
    amount: "Amount",
    deliveredAmount: "Delivered amount",
    sourceTag: "Source Tag",
    destinationTag: "Destination Tag",
    absent: "Not present",
    digest: "Proof digest",
    digestBody: "This identifier is derived from normalized immutable receipt facts and retrieves this public proof.",
    pageEyebrow: "Public verified receipt",
    pageTitle: "Inspect the immutable facts behind a verified payment.",
    pageBody: "The proof identifier stays in this URL fragment. The page reveals only public XRP Ledger facts and never exposes private bill or participant details.",
  },
  ja: {
    loading: "トランザクション証明を読み込み中",
    unavailable: "トランザクション証明を利用できません",
    invalid: "証明リンクが不完全または無効です。新しい検証済み支払いリンクを受け取ってください。",
    fallback: "トランザクション証明を読み込めませんでした。",
    retry: "再試行",
    privacy: "証明ページには公開台帳情報だけが含まれ、非公開の請求情報は含まれません。",
    verified: "台帳検証済み",
    delivered: "{amount} XRPを送付済み",
    summary: "このレシートは検証済み台帳で確認された成功XRP Paymentを記録し、公開トランザクション情報だけを含みます。",
    validation: "検証状態",
    validated: "検証済み",
    result: "結果",
    ledger: "Ledger index",
    facts: "検証済みトランザクション情報",
    factsBody: "請求名、参加者名、支払い前の想定情報、運用時刻、Xaman payload識別子は含まれません。",
    transaction: "トランザクションID",
    invoice: "InvoiceID",
    sender: "送金元",
    destination: "送金先",
    amount: "金額",
    deliveredAmount: "実際の送付額",
    sourceTag: "Source Tag",
    destinationTag: "Destination Tag",
    absent: "なし",
    digest: "証明ダイジェスト",
    digestBody: "この識別子は正規化された不変レシート情報から生成され、この公開証明の取得に使用されます。",
    pageEyebrow: "公開検証レシート",
    pageTitle: "検証済み支払いを構成する不変の事実を確認します。",
    pageBody: "証明識別子はURLフラグメント内に保持されます。このページは公開XRP Ledger情報だけを表示し、非公開の請求・参加者情報は公開しません。",
  },
  ko: {
    loading: "트랜잭션 증명 불러오는 중",
    unavailable: "트랜잭션 증명을 사용할 수 없습니다",
    invalid: "증명 링크가 불완전하거나 유효하지 않습니다. 새 검증 결제 링크를 요청하세요.",
    fallback: "트랜잭션 증명을 불러올 수 없습니다.",
    retry: "다시 시도",
    privacy: "증명 페이지에는 공개 원장 사실만 포함되며 비공개 청구서 정보는 포함되지 않습니다.",
    verified: "원장 검증 완료",
    delivered: "{amount} XRP 전달 완료",
    summary: "이 영수증은 검증된 원장에서 확인된 성공한 XRP Payment를 기록하며 공개 트랜잭션 사실만 포함합니다.",
    validation: "검증",
    validated: "검증됨",
    result: "결과",
    ledger: "Ledger index",
    facts: "검증된 트랜잭션 사실",
    factsBody: "청구서 제목, 참가자 이름, 결제 전 예상 정보, 운영 타임스탬프, Xaman payload 식별자는 포함하지 않습니다.",
    transaction: "트랜잭션 ID",
    invoice: "InvoiceID",
    sender: "보낸 사람",
    destination: "수취인",
    amount: "금액",
    deliveredAmount: "전달 금액",
    sourceTag: "Source Tag",
    destinationTag: "Destination Tag",
    absent: "없음",
    digest: "증명 다이제스트",
    digestBody: "이 식별자는 정규화된 변경 불가능 영수증 사실에서 파생되며 이 공개 증명을 조회하는 데 사용됩니다.",
    pageEyebrow: "공개 검증 영수증",
    pageTitle: "검증된 결제의 변경 불가능한 사실을 확인하세요.",
    pageBody: "증명 식별자는 URL 프래그먼트에 유지됩니다. 이 페이지는 공개 XRP Ledger 사실만 보여주며 비공개 청구서나 참가자 정보를 노출하지 않습니다.",
  },
} as const;

export type ProofMessageKey = keyof typeof catalogs.en;

export function proofTranslate(locale: Locale, key: ProofMessageKey, variables: Record<string, string | number> = {}) {
  return catalogs[locale][key].replace(/\{([A-Za-z0-9_]+)\}/g, (_, name: string) => Object.prototype.hasOwnProperty.call(variables, name) ? String(variables[name]) : `{${name}}`);
}

export function useProofLocalization() {
  const { locale } = useLocalization();
  return { pt: (key: ProofMessageKey, variables?: Record<string, string | number>) => proofTranslate(locale, key, variables) };
}
