import type { Locale } from "./catalog";

const copy = {
  en: {
    title: "Payment readiness",
    body: "Group Pay checks the payer and recipient on a validated XRPL ledger before creating a wallet request.",
    payer: "Payer wallet",
    recipient: "Recipient account",
    ready: "Ready",
    blocked: "Action required",
    unavailable: "Temporarily unavailable",
    checking: "Checking",
    recheck: "Recheck readiness",
    setup: "Prepare official RLUSD TrustSet",
    openSetup: "Open RLUSD setup",
    setupWorking: "Preparing setup",
    setupNotice: "TrustSet configures the official RLUSD trust line. It does not provide RLUSD and it does not pay this Bill.",
    unavailableBody: "Validated ledger data is temporarily unavailable. This is not a claim that the wallet has insufficient funds.",
    account: "Account exists",
    spendable: "Spendable XRP",
    fee: "Estimated fee",
    reserve: "Current reserve",
    trustLine: "Official RLUSD trust line",
    assetBalance: "RLUSD balance",
    nativeBalance: "XRP payment capacity",
    current: "Current",
    required: "Required",
    missing: "Missing",
    recipientReady: "Recipient can receive this payment",
    blocked_account_not_found: "The XRPL account was not found on the validated ledger.",
    blocked_insufficient_spendable_xrp: "The payer does not currently have enough spendable XRP for the payment, fee, and reserve constraints.",
    blocked_trust_line_missing: "The payer does not have the official RLUSD trust line.",
    blocked_trust_line_frozen: "The official RLUSD trust line is frozen.",
    blocked_trust_line_not_authorized: "The official RLUSD trust line is not authorized.",
    blocked_issued_balance_insufficient: "The payer does not currently have enough RLUSD.",
    blocked_issuer_global_freeze: "The official RLUSD issuer is globally frozen.",
    blocked_destination_tag_required: "The recipient requires a Destination Tag.",
    blocked_deposit_authorization_required: "The recipient requires deposit authorization.",
    blocked_trust_line_limit_insufficient: "The recipient trust line cannot receive the required amount.",
    blocked_default: "A confirmed XRPL condition must be resolved before payment can continue.",
  },
  ja: {
    title: "支払い準備状態",
    body: "ウォレットリクエストを作成する前に、検証済みXRPL台帳で支払者と受取人を確認します。",
    payer: "支払者ウォレット",
    recipient: "受取先アカウント",
    ready: "準備完了",
    blocked: "対応が必要",
    unavailable: "一時的に確認できません",
    checking: "確認中",
    recheck: "準備状態を再確認",
    setup: "公式RLUSD TrustSetを準備",
    openSetup: "RLUSD準備画面を開く",
    setupWorking: "準備画面を作成中",
    setupNotice: "TrustSetは公式RLUSDトラストラインを設定します。RLUSDは付与されず、この請求の支払いも行われません。",
    unavailableBody: "検証済み台帳データを一時的に取得できません。残高不足を意味する表示ではありません。",
    account: "アカウントの存在",
    spendable: "利用可能XRP",
    fee: "推定手数料",
    reserve: "現在のリザーブ",
    trustLine: "公式RLUSDトラストライン",
    assetBalance: "RLUSD残高",
    nativeBalance: "XRP支払い能力",
    current: "現在",
    required: "必要",
    missing: "不足",
    recipientReady: "受取人はこの支払いを受け取れます",
    blocked_account_not_found: "検証済み台帳でXRPLアカウントを確認できませんでした。",
    blocked_insufficient_spendable_xrp: "支払額、手数料、リザーブ条件を満たす利用可能XRPが不足しています。",
    blocked_trust_line_missing: "公式RLUSDトラストラインがありません。",
    blocked_trust_line_frozen: "公式RLUSDトラストラインが凍結されています。",
    blocked_trust_line_not_authorized: "公式RLUSDトラストラインが承認されていません。",
    blocked_issued_balance_insufficient: "RLUSD残高が不足しています。",
    blocked_issuer_global_freeze: "公式RLUSD発行者がグローバルフリーズ状態です。",
    blocked_destination_tag_required: "受取人にはDestination Tagが必要です。",
    blocked_deposit_authorization_required: "受取人には入金承認が必要です。",
    blocked_trust_line_limit_insufficient: "受取人のトラストラインでは必要額を受け取れません。",
    blocked_default: "支払いを続ける前に、確認済みのXRPL上の問題を解消する必要があります。",
  },
  ko: {
    title: "결제 준비 상태",
    body: "지갑 요청을 만들기 전에 검증된 XRPL 원장에서 결제자와 수취인을 확인합니다.",
    payer: "결제자 지갑",
    recipient: "수취인 계정",
    ready: "준비 완료",
    blocked: "조치 필요",
    unavailable: "일시적으로 확인할 수 없음",
    checking: "확인 중",
    recheck: "준비 상태 다시 확인",
    setup: "공식 RLUSD TrustSet 준비",
    openSetup: "RLUSD 설정 열기",
    setupWorking: "설정 준비 중",
    setupNotice: "TrustSet은 공식 RLUSD 트러스트라인을 설정합니다. RLUSD를 제공하지 않으며 이 청구를 결제하지도 않습니다.",
    unavailableBody: "검증된 원장 데이터를 일시적으로 가져올 수 없습니다. 잔액 부족을 의미하지 않습니다.",
    account: "계정 존재",
    spendable: "사용 가능 XRP",
    fee: "예상 수수료",
    reserve: "현재 준비금",
    trustLine: "공식 RLUSD 트러스트라인",
    assetBalance: "RLUSD 잔액",
    nativeBalance: "XRP 결제 가능 금액",
    current: "현재",
    required: "필요",
    missing: "부족",
    recipientReady: "수취인이 이 결제를 받을 수 있습니다",
    blocked_account_not_found: "검증된 원장에서 XRPL 계정을 찾을 수 없습니다.",
    blocked_insufficient_spendable_xrp: "결제 금액, 수수료와 준비금 조건을 충족할 사용 가능 XRP가 부족합니다.",
    blocked_trust_line_missing: "공식 RLUSD 트러스트라인이 없습니다.",
    blocked_trust_line_frozen: "공식 RLUSD 트러스트라인이 동결되었습니다.",
    blocked_trust_line_not_authorized: "공식 RLUSD 트러스트라인이 승인되지 않았습니다.",
    blocked_issued_balance_insufficient: "RLUSD 잔액이 부족합니다.",
    blocked_issuer_global_freeze: "공식 RLUSD 발행자가 글로벌 동결 상태입니다.",
    blocked_destination_tag_required: "수취인에게 Destination Tag가 필요합니다.",
    blocked_deposit_authorization_required: "수취인에게 입금 승인이 필요합니다.",
    blocked_trust_line_limit_insufficient: "수취인 트러스트라인이 필요한 금액을 받을 수 없습니다.",
    blocked_default: "결제를 계속하기 전에 확인된 XRPL 조건을 해결해야 합니다.",
  },
} as const;

export type ReadinessMessageKey = keyof (typeof copy)["en"];

export function readinessTranslate(locale: Locale, key: ReadinessMessageKey) {
  return copy[locale]?.[key] ?? copy.en[key];
}

export function readinessReason(locale: Locale, code: string | null) {
  const key = `blocked_${code ?? "default"}` as ReadinessMessageKey;
  return key in copy.en
    ? readinessTranslate(locale, key)
    : readinessTranslate(locale, "blocked_default");
}
