import type { PaymentRecoveryAssessment } from "@/features/payment-recovery/taxonomy";

import type { Locale } from "./catalog";

const en = {
  "recovery.disposition.safe_retry.title": "Safe to create a new request",
  "recovery.disposition.safe_retry.action": "Review and try again",
  "recovery.disposition.wait_recheck.title": "Wait and check again",
  "recovery.disposition.wait_recheck.action": "Check again",
  "recovery.disposition.setup_required.title": "Wallet setup is required",
  "recovery.disposition.setup_required.action": "Review setup steps",
  "recovery.disposition.review_required.title": "Manual review is required",
  "recovery.disposition.already_paid.title": "Payment is already recorded",
  "recovery.disposition.terminal.title": "This payment cannot continue",
  "recovery.reason.payerCancelled": "The payer cancelled before a settlement transaction was submitted. A replacement request may be created only after the standard reconciliation check.",
  "recovery.reason.handoffExpired": "The wallet request expired before a settlement transaction was submitted. A fresh request may be created only after the standard reconciliation check.",
  "recovery.reason.handoffProviderFailed": "The wallet provider reported a failure without a confirmed transaction. Do not create a replacement until the provider state can be checked again.",
  "recovery.reason.providerUnavailable": "The wallet provider is temporarily unavailable. No new request should be created until the existing request state can be checked.",
  "recovery.reason.ledgerUnavailable": "Validated XRP Ledger data is temporarily unavailable. Keep the current state and check again later.",
  "recovery.reason.transactionPending": "A submitted transaction has not appeared in a validated ledger yet. Do not create another payment while confirmation is pending.",
  "recovery.reason.transactionFailed": "The transaction was validated with a failure result, so it did not satisfy this payment slot. Reconciliation is still required before creating a replacement.",
  "recovery.reason.invalidProviderHandoff": "The wallet provider state and transaction identity are inconsistent. A replacement could cause a duplicate payment, so this case requires review.",
  "recovery.reason.unsupportedVerification": "This payment cannot be verified by the enabled verification strategy.",
  "recovery.reason.paymentMismatch": "The observed transaction does not match the frozen payment contract. It cannot be accepted or automatically retried.",
  "recovery.reason.wrongSigner": "The validated transaction was signed by a different account from the frozen payer account.",
  "recovery.reason.wrongDestination": "The validated transaction sent funds to a different destination from the frozen recipient account.",
  "recovery.reason.wrongAmount": "The requested or delivered amount does not match the frozen payment amount.",
  "recovery.reason.wrongAsset": "The validated transaction used a different asset, currency, or issuer from the frozen payment asset.",
  "recovery.reason.wrongTags": "The Source Tag or Destination Tag does not match the frozen payment contract.",
  "recovery.reason.wrongInvoice": "The InvoiceID does not match the frozen payment slot.",
  "recovery.reason.partialPayment": "Partial Payment is not supported for Group Pay slots. The transaction requires review and cannot mark the slot paid.",
  "recovery.reason.crossCurrencyPayment": "Cross-currency delivery is not supported for Group Pay slots. The transaction requires review.",
  "recovery.reason.accountNotFound": "The XRPL account does not exist on the selected network and must be activated before continuing.",
  "recovery.reason.destinationTagRequired": "The recipient account requires a Destination Tag. The bill must include the correct tag before payment links are created.",
  "recovery.reason.depositAuthorizationRequired": "The recipient account requires Deposit Authorization and is not currently ready to receive this payment.",
  "recovery.reason.trustLineMissing": "The wallet does not have the official network-specific RLUSD trust line required for this payment.",
  "recovery.reason.trustLineLimitInsufficient": "The official RLUSD trust-line limit is too low for the amount that must be received.",
  "recovery.reason.trustLineFrozen": "The official RLUSD trust line is frozen or deep-frozen. A new TrustSet request cannot remove this restriction.",
  "recovery.reason.trustLineNotAuthorized": "The official RLUSD trust line requires issuer authorization before it can be used.",
  "recovery.reason.issuerUnavailable": "The configured official RLUSD issuer account is unavailable on the selected network.",
  "recovery.reason.issuerGlobalFreeze": "The official RLUSD issuer has enabled Global Freeze, so this payment cannot continue.",
  "recovery.reason.insufficientRlusd": "The payer does not hold enough official RLUSD for the frozen payment amount. TrustSet alone does not add funds.",
  "recovery.reason.insufficientSpendableXrp": "The wallet does not have enough spendable XRP after reserve requirements to cover the payment and network fee.",
  "recovery.reason.trustLineDataInvalid": "The observed trust-line data could not be interpreted safely and requires review.",
  "recovery.reason.duplicatePayment": "A validated transaction already satisfies this payment slot. Do not create or submit another payment.",
  "recovery.reason.multipleCandidates": "Multiple validated transactions may satisfy this payment slot. Automatic replacement is blocked until the case is reviewed.",
  "recovery.reason.activeHandoffExists": "An active wallet request already exists for this payment slot. Resume or check that request instead of creating another one.",
  "recovery.reason.billClosed": "This bill is closed or no longer accepts new payment activity.",
  "recovery.reason.unknownFailure": "The payment state could not be classified safely. Keep the current state and request review.",
} as const;

export type RecoveryMessageKey = keyof typeof en;
type RecoveryCatalog = Record<RecoveryMessageKey, string>;

const ja: RecoveryCatalog = {
  "recovery.disposition.safe_retry.title": "新しい要求を安全に作成できます",
  "recovery.disposition.safe_retry.action": "内容を確認して再試行",
  "recovery.disposition.wait_recheck.title": "待ってから再確認してください",
  "recovery.disposition.wait_recheck.action": "再確認",
  "recovery.disposition.setup_required.title": "ウォレットの準備が必要です",
  "recovery.disposition.setup_required.action": "準備手順を確認",
  "recovery.disposition.review_required.title": "個別確認が必要です",
  "recovery.disposition.already_paid.title": "支払いは記録済みです",
  "recovery.disposition.terminal.title": "この支払いは続行できません",
  "recovery.reason.payerCancelled": "支払者が精算トランザクション送信前にキャンセルしました。通常の照合を行った後にのみ新しい要求を作成できます。",
  "recovery.reason.handoffExpired": "精算トランザクション送信前にウォレット要求の期限が切れました。通常の照合を行った後にのみ新しい要求を作成できます。",
  "recovery.reason.handoffProviderFailed": "確認済みトランザクションがない状態でウォレット提供元が失敗を報告しました。既存要求の状態を再確認できるまで新しい要求を作成しないでください。",
  "recovery.reason.providerUnavailable": "ウォレット提供元を一時的に利用できません。既存要求の状態を確認できるまで新しい要求を作成しないでください。",
  "recovery.reason.ledgerUnavailable": "検証済みXRP Ledgerデータを一時的に取得できません。現在の状態を維持して後でもう一度確認してください。",
  "recovery.reason.transactionPending": "送信済みトランザクションがまだ検証済みLedgerに現れていません。確定待ちの間は別の支払いを作成しないでください。",
  "recovery.reason.transactionFailed": "トランザクションは失敗結果で検証され、この支払い枠を満たしていません。新しい要求を作る前に照合が必要です。",
  "recovery.reason.invalidProviderHandoff": "ウォレット提供元の状態とトランザクション識別子が一致しません。二重払いを避けるため、新しい要求を作らず個別確認してください。",
  "recovery.reason.unsupportedVerification": "有効な検証方式ではこの支払いを検証できません。",
  "recovery.reason.paymentMismatch": "確認されたトランザクションが固定済み支払い契約と一致しません。支払済みとして扱えず、自動再試行もできません。",
  "recovery.reason.wrongSigner": "検証済みトランザクションの署名者が固定された支払者口座と異なります。",
  "recovery.reason.wrongDestination": "検証済みトランザクションの送金先が固定された受取人口座と異なります。",
  "recovery.reason.wrongAmount": "要求額または実際の到着額が固定された支払額と一致しません。",
  "recovery.reason.wrongAsset": "検証済みトランザクションの資産、通貨、または発行元が固定された決済資産と異なります。",
  "recovery.reason.wrongTags": "Source TagまたはDestination Tagが固定済み支払い契約と一致しません。",
  "recovery.reason.wrongInvoice": "InvoiceIDが固定された支払い枠と一致しません。",
  "recovery.reason.partialPayment": "Group Payの支払い枠はPartial Paymentに対応していません。個別確認が必要で、支払済みにはできません。",
  "recovery.reason.crossCurrencyPayment": "Group Payの支払い枠は異なる通貨からの変換送金に対応していません。個別確認が必要です。",
  "recovery.reason.accountNotFound": "選択したネットワークにXRPL口座が存在しません。続行前に口座を有効化する必要があります。",
  "recovery.reason.destinationTagRequired": "受取人口座にはDestination Tagが必要です。支払いリンク作成前に正しいTagを請求へ設定してください。",
  "recovery.reason.depositAuthorizationRequired": "受取人口座でDeposit Authorizationが必要なため、現在この支払いを受け取れません。",
  "recovery.reason.trustLineMissing": "この支払いに必要なネットワーク別公式RLUSDトラストラインがありません。",
  "recovery.reason.trustLineLimitInsufficient": "公式RLUSDトラストラインの上限が受取予定額に対して不足しています。",
  "recovery.reason.trustLineFrozen": "公式RLUSDトラストラインが凍結またはDeep Freezeされています。新しいTrustSetでは解除できません。",
  "recovery.reason.trustLineNotAuthorized": "公式RLUSDトラストラインを利用するには発行元の承認が必要です。",
  "recovery.reason.issuerUnavailable": "設定された公式RLUSD発行元口座を選択したネットワークで確認できません。",
  "recovery.reason.issuerGlobalFreeze": "公式RLUSD発行元がGlobal Freezeを有効にしているため、この支払いは続行できません。",
  "recovery.reason.insufficientRlusd": "支払者の公式RLUSD残高が固定支払額に足りません。TrustSetだけでは残高は増えません。",
  "recovery.reason.insufficientSpendableXrp": "口座準備金を差し引いた利用可能XRPが、支払額とネットワーク手数料を賄うには不足しています。",
  "recovery.reason.trustLineDataInvalid": "確認されたトラストライン情報を安全に解釈できないため、個別確認が必要です。",
  "recovery.reason.duplicatePayment": "この支払い枠を満たす検証済みトランザクションがすでにあります。別の支払いを作成・送信しないでください。",
  "recovery.reason.multipleCandidates": "この支払い枠を満たす可能性がある検証済みトランザクションが複数あります。確認が終わるまで自動再発行を停止します。",
  "recovery.reason.activeHandoffExists": "この支払い枠には有効なウォレット要求がすでにあります。新規作成せず、既存要求を再開または確認してください。",
  "recovery.reason.billClosed": "この請求は終了済みか、新しい支払いを受け付けていません。",
  "recovery.reason.unknownFailure": "支払い状態を安全に分類できませんでした。現在の状態を維持して個別確認してください。",
};

const ko: RecoveryCatalog = {
  "recovery.disposition.safe_retry.title": "새 요청을 안전하게 만들 수 있습니다",
  "recovery.disposition.safe_retry.action": "내용 확인 후 다시 시도",
  "recovery.disposition.wait_recheck.title": "기다린 후 다시 확인하세요",
  "recovery.disposition.wait_recheck.action": "다시 확인",
  "recovery.disposition.setup_required.title": "지갑 준비가 필요합니다",
  "recovery.disposition.setup_required.action": "준비 단계 확인",
  "recovery.disposition.review_required.title": "개별 검토가 필요합니다",
  "recovery.disposition.already_paid.title": "결제가 이미 기록되었습니다",
  "recovery.disposition.terminal.title": "이 결제를 계속할 수 없습니다",
  "recovery.reason.payerCancelled": "결제자가 정산 트랜잭션 제출 전에 취소했습니다. 표준 대조 확인 후에만 새 요청을 만들 수 있습니다.",
  "recovery.reason.handoffExpired": "정산 트랜잭션 제출 전에 지갑 요청이 만료되었습니다. 표준 대조 확인 후에만 새 요청을 만들 수 있습니다.",
  "recovery.reason.handoffProviderFailed": "확인된 트랜잭션 없이 지갑 제공자가 실패를 보고했습니다. 기존 요청 상태를 다시 확인할 수 있을 때까지 새 요청을 만들지 마세요.",
  "recovery.reason.providerUnavailable": "지갑 제공자를 일시적으로 사용할 수 없습니다. 기존 요청 상태를 확인할 때까지 새 요청을 만들지 마세요.",
  "recovery.reason.ledgerUnavailable": "검증된 XRP Ledger 데이터를 일시적으로 가져올 수 없습니다. 현재 상태를 유지하고 나중에 다시 확인하세요.",
  "recovery.reason.transactionPending": "제출된 트랜잭션이 아직 검증된 원장에 나타나지 않았습니다. 확인 대기 중에는 다른 결제를 만들지 마세요.",
  "recovery.reason.transactionFailed": "트랜잭션이 실패 결과로 검증되어 이 결제 슬롯을 충족하지 못했습니다. 새 요청 전 대조 확인이 필요합니다.",
  "recovery.reason.invalidProviderHandoff": "지갑 제공자 상태와 트랜잭션 식별자가 일치하지 않습니다. 중복 결제를 막기 위해 새 요청을 만들지 말고 검토하세요.",
  "recovery.reason.unsupportedVerification": "활성화된 검증 방식으로 이 결제를 확인할 수 없습니다.",
  "recovery.reason.paymentMismatch": "관찰된 트랜잭션이 고정된 결제 계약과 일치하지 않습니다. 결제 완료로 인정하거나 자동 재시도할 수 없습니다.",
  "recovery.reason.wrongSigner": "검증된 트랜잭션의 서명 계정이 고정된 결제자 계정과 다릅니다.",
  "recovery.reason.wrongDestination": "검증된 트랜잭션의 목적지가 고정된 수취인 계정과 다릅니다.",
  "recovery.reason.wrongAmount": "요청 금액 또는 실제 전달 금액이 고정된 결제 금액과 일치하지 않습니다.",
  "recovery.reason.wrongAsset": "검증된 트랜잭션의 자산, 통화 또는 발행자가 고정된 결제 자산과 다릅니다.",
  "recovery.reason.wrongTags": "Source Tag 또는 Destination Tag가 고정된 결제 계약과 일치하지 않습니다.",
  "recovery.reason.wrongInvoice": "InvoiceID가 고정된 결제 슬롯과 일치하지 않습니다.",
  "recovery.reason.partialPayment": "Group Pay 결제 슬롯은 Partial Payment를 지원하지 않습니다. 검토가 필요하며 결제 완료로 표시할 수 없습니다.",
  "recovery.reason.crossCurrencyPayment": "Group Pay 결제 슬롯은 교차 통화 전달을 지원하지 않습니다. 개별 검토가 필요합니다.",
  "recovery.reason.accountNotFound": "선택한 네트워크에 XRPL 계정이 없습니다. 계속하기 전에 계정을 활성화해야 합니다.",
  "recovery.reason.destinationTagRequired": "수취인 계정에 Destination Tag가 필요합니다. 결제 링크를 만들기 전에 올바른 Tag를 청구서에 설정하세요.",
  "recovery.reason.depositAuthorizationRequired": "수취인 계정에 Deposit Authorization이 필요하여 현재 이 결제를 받을 준비가 되지 않았습니다.",
  "recovery.reason.trustLineMissing": "이 결제에 필요한 네트워크별 공식 RLUSD 신뢰선이 없습니다.",
  "recovery.reason.trustLineLimitInsufficient": "공식 RLUSD 신뢰선 한도가 받아야 할 금액보다 낮습니다.",
  "recovery.reason.trustLineFrozen": "공식 RLUSD 신뢰선이 동결되었거나 Deep Freeze 상태입니다. 새 TrustSet 요청으로 해제할 수 없습니다.",
  "recovery.reason.trustLineNotAuthorized": "공식 RLUSD 신뢰선을 사용하려면 발행자의 승인이 필요합니다.",
  "recovery.reason.issuerUnavailable": "선택한 네트워크에서 설정된 공식 RLUSD 발행자 계정을 확인할 수 없습니다.",
  "recovery.reason.issuerGlobalFreeze": "공식 RLUSD 발행자가 Global Freeze를 활성화하여 이 결제를 계속할 수 없습니다.",
  "recovery.reason.insufficientRlusd": "결제자의 공식 RLUSD 잔액이 고정 결제 금액보다 적습니다. TrustSet만으로 잔액이 늘어나지 않습니다.",
  "recovery.reason.insufficientSpendableXrp": "계정 준비금을 제외한 사용 가능 XRP가 결제 금액과 네트워크 수수료를 충당하기에 부족합니다.",
  "recovery.reason.trustLineDataInvalid": "관찰된 신뢰선 데이터를 안전하게 해석할 수 없어 개별 검토가 필요합니다.",
  "recovery.reason.duplicatePayment": "이 결제 슬롯을 충족하는 검증된 트랜잭션이 이미 있습니다. 다른 결제를 만들거나 제출하지 마세요.",
  "recovery.reason.multipleCandidates": "이 결제 슬롯을 충족할 수 있는 검증된 트랜잭션이 여러 개 있습니다. 검토가 끝날 때까지 자동 재발행이 차단됩니다.",
  "recovery.reason.activeHandoffExists": "이 결제 슬롯에 활성 지갑 요청이 이미 있습니다. 새로 만들지 말고 기존 요청을 다시 열거나 확인하세요.",
  "recovery.reason.billClosed": "이 청구서는 종료되었거나 더 이상 새 결제를 받지 않습니다.",
  "recovery.reason.unknownFailure": "결제 상태를 안전하게 분류할 수 없습니다. 현재 상태를 유지하고 개별 검토를 요청하세요.",
};

const catalogs: Record<Locale, RecoveryCatalog> = { en, ja, ko };

export function recoveryTranslate(locale: Locale, key: RecoveryMessageKey) {
  return catalogs[locale]?.[key] ?? en[key];
}

export function paymentRecoveryCopy(
  locale: Locale,
  assessment: PaymentRecoveryAssessment,
) {
  return {
    title: recoveryTranslate(locale, assessment.titleKey),
    body: recoveryTranslate(locale, assessment.bodyKey),
    action: assessment.actionKey
      ? recoveryTranslate(locale, assessment.actionKey)
      : null,
  };
}
